### ISSUE TITLE
util.inspect() no longer logs to console after applying log4js

### ISSUE THREAD

**Issue by icelava** [nomiddlename/log4js-node#104]
Previously I was logging information directly to Node's console using util.log() and util.inspect() for debugging entire object graphs.

After using log4js to implement file logging, it appears util.inspect() no longer logs anything to anywhere. The setup code goes

//log4js.replaceConsole();
log4js.configure({
    appenders: [
        { type: 'console' },
        { type: 'file', filename: 'log/socket.log', category: 'socket' }
    ]
});
var logger = log4js.getLogger('socket');

The behaviour is the same regardless of the call to replaceConsole().

**Comment by nomiddlename** [comment]
Closing this one, because it's very old, and log4js doesn't do anything to util.inspect, and as far as I know util.inspect never logged anything directly anyway. Please re-open if this is still an issue.
