### ISSUE TITLE
dateFile appender stops writing to file when tailing logfile after rotation

### ISSUE THREAD

**Issue by stiang** [nomiddlename/log4js-node#118]
We use the dateFile appender with the following config:

``` json
{
  "appenders": [
    { 
      "type": "dateFile",
      "filename": "/var/log/foo-server.log",
      "pattern": "-yyyy-MM-dd",
      "backups": 2
    }
  ],
  "levels": {
    "server": "WARN"
  }
}
```

The logfile is rotated as per the config and everything appears to work just fine, but if I "tail -f" the currently active log file after it has been rotated, node will stop writing to it at the precise moment when I access the file. If I restart node I can "tail -f" the active log file just fine, but only until it gets rotated.

Versions:
- log4js v0.5.6
- node v0.8.19
- Ubuntu 12.04.2 LTS (GNU/Linux 3.2.0-37-virtual x86_64)

**Comment by svnindia** [comment]
Same things happens for me too... Is there a solution ?

Yesterdays log file has todays 3 line of logs and todays logs are not going to the expected log file.

I am using log4js with Sails & PM2.

**Comment by vphantom** [comment]
You need to use `tail -F` not `tail -f` if you want to follow files by name through a rotation.

**Comment by nomiddlename** [comment]
Problems with log rotation are usually due to multiple processes attempting to rotate the logs. If this is the case, version 2 has better support for cluster logging. Closing this one, please re-open if this problem still occurs in version 2.
