### ISSUE TITLE
Can log4js have a custom log function?

### ISSUE THREAD

**Issue by XadillaX** [nomiddlename/log4js-node#146]
You see, there're trace, debug, info, warn, error and fetal.

But if I want custom a new message type and color, how should I do?

for example, I want have a "success" with green color or I want have a "foo" with bar color.

**Comment by nomiddlename** [comment]
This is another version of #254 - a feature I'll add in version 2.x

**Comment by nomiddlename** [comment]
Released in version 2.0.0
