### ISSUE TITLE
Configure level per appender

### ISSUE THREAD

**Issue by vojtajina** [nomiddlename/log4js-node#153]
Is there a way how to configure multiple appenders - each having a different level ?

**Comment by leegee** [comment]
Did this never get released?
TIA
Lee

**Comment by nomiddlename** [comment]
I think log level filters do the same job, and you can specify a min log level and a max log level on them. There's also a category filter as well.

**Comment by leegee** [comment]
Can a log level or category filter restrict a specific appender to logging messages on or above a specific level?

**Comment by nomiddlename** [comment]
Closing this one, as logLevelFilter and categoryFilter do the job (and in version 2.x setting levels for categories becomes a bit more explicit).

**Comment by leegee** [comment]
Could you please post a link to an illustrative example?

**Comment by nomiddlename** [comment]
Hi @leegee  - the log4js example application uses a log level filter. Take a look at the [config](https://github.com/nomiddlename/log4js-example/blob/master/config/log4js.json) - does that help?

**Comment by leegee** [comment]
Yes, but why not put it in the docs?
