### ISSUE TITLE
Would be useful to be able to set the default date format

### ISSUE THREAD

**Issue by nickminutello** [nomiddlename/log4js-node#155]
We currently used the console appender with the coloured layout (The default. We don't specify anything).

The coloured layout uses the 'default' date format - which is ISO8601_FORMAT (yyyy-MM-dd hh:mm:ss.SSS).

I would like the default date format to include the timezone offset - ie yyyy-MM-dd hh:mm:ss.SSSO.

There seems to be no way to do this without going to the effort of using the pattern layout....
Would be nicer just to be able to set the default date format ...

**Comment by filsmick** [comment]
Thanks @tcdaly, this really needs to be implemented.

**Comment by docksteaderluke** [comment]
+1

Any update on this?

**Comment by nomiddlename** [comment]
There's already a way to specify the date format, by supplying your own layout function (or using the pattern layout).
