### ISSUE TITLE
Is it possible to force flush the buffered logs?

### ISSUE THREAD

**Issue by manish-alphonso-tv** [nomiddlename/log4js-node#159]
Is it possible to force flush the buffered logs?

I have a compute intensive long running process. I see hours worth of logs stay buffered somewhere and don't get flushed to file on disk. I am looking for means to force flush the output (or disable the buffering).

**Comment by Smurf-IV** [comment]
Just come across this problem for the Rolling appender.
What happens in a crash situation ? ,Or an uncaught exception?
Will the logged information get flushed then? How can it. It just crashed !

**Comment by Smurf-IV** [comment]
The following is supposed to "catch" the abort situation via an uncaught exception handler, so that it gives the logging a chance to end.. Not tested yet, as i am still "waiting" for another exception to occur.
```
// istanbul ignore next: Should never hit this, in a unit test environment
function uncaughtApplicationHandler() {
	// uncaught application handler for proper logging
	process.on('uncaughtException', function (err) {
		/*eslint-disable */
		console.log(err.stack || err.message || err);
		log4js.getDefaultLogger().fatal('uncaughtException', err.stack || err.message || err);
		log4js.shutdown(function () { process.exit(1); }); // to abort application
		/*eslint-enable */
	});}
```

**Comment by nomiddlename** [comment]
Going to close this as the original issue was a request for synchronous appenders, which was done a while ago. There may be a separate issue for the lack of shutdown support for synchronous appenders, but maybe that isn't necessary as they should write to files as soon as they get called.

**Comment by emouawad** [comment]
@nomiddlename  I understand there are synchronous appenders - will they work with a dateFile?

**Comment by nomiddlename** [comment]
@emouawad there is no synchronous dateFile appender, sorry. But it looks like node now has a 'rs+' option for the file flags which will flush output to files even when using the asynchronous APIs.
