### ISSUE TITLE
Error: Cannot find module 'semver'

### ISSUE THREAD

**Issue by raymondZhong** [nomiddlename/log4js-node#166]
my code
<hr/>
var log4js = require('node-log4js/log4js.js');
log4js.configure({
  appenders: [
    { type: 'file', filename: 'cheese.log', category: 'cheese' }
  ]
});
<hr/>
error:
Error: Cannot find module 'semver'

**Comment by nomiddlename** [comment]
Closing this one. `semver` has been a dependency for ages.
