### ISSUE TITLE
SMTP appender could be smarter about mail timing

### ISSUE THREAD

**Issue by wmertens** [nomiddlename/log4js-node#169]
Right now the SMTP appender sends each message directly, or it pools up messages for an interval and then sends them.

The problem is the initial error transmission delay: Suppose you're entering a failure condition which causes frequent error messages. Ops needs to know about that ASAP,  but they don't want to get deluged by email so they don't want a small interval. So if you pick a large interval there are less emails but it takes too long before Ops gets notified about the initial error.

The solution is to make the first interval be tiny, say 10 seconds, so that the initial error plus any related messages get sent out immediately, and then the normal interval (e.g. 30 minutes) gets used. Once there is an entire interval without errors, the small 10s interval should be used again.

Thoughts?

**Comment by nomiddlename** [comment]
Closing this, happy to re-open is someone implements it.
