### ISSUE TITLE
Unhandled Exception handling

### ISSUE THREAD

**Issue by blak3r** [nomiddlename/log4js-node#170]
Winston has a "handleExceptions" property that was pretty handy.
Wondering what the log4js way is for catching unhandled exceptions which will make your application crash.

I did some searching and came up with this solution.  I added the following snippet to my logger.js file which is the file all my application code includes.  Is this a good approach?

```
process.on('uncaughtException', function(err) {
    // log error then exit
    logger.fatal(err);
    process.exit(1);
});
```

**Comment by Smurf-IV** [comment]
Node documentation has changed to state that when an catching that _exception _to "**not**" resume; Quote:
```
Note that 'uncaughtException' is a very crude mechanism for exception handling.
Do not use it as the Node.js equivalent of On Error Resume Next. An unhandled exception means your application - and by extension Node.js itself - is in an undefined state. Blindly resuming means anything could happen. 
```

**Comment by nomiddlename** [comment]
I'm going to close this one, since the `process.on('uncaught...')` method is a workaround. Happy to re-open if someone has a better suggestion or a different opinion.
