### ISSUE TITLE
appender file error 

### ISSUE THREAD

**Issue by sishao** [nomiddlename/log4js-node#174]
when i tested the appender of file ,snippet code like something below:

//log4js
var log4js = require('log4js');
log4js.configure({
  appenders: [
    { type: 'console' },
    {
        type: 'file',
        filename: 'logs/cheese.log',
        "maxLogSize": 20480,
        "backups": 3,
        category: 'cheese'
    }
  ]
});
var logger = log4js.getLogger('cheese');
//test
for(var i = 0;i<10000000;i++)
{
   logger.debug("Some debug messages");
}

after it runs several minutes ,there are no file at the logs/ directory

so i wonder why ?

**Comment by nomiddlename** [comment]
No more information provided, so closing this issue.
