### ISSUE TITLE
One log file per user session

### ISSUE THREAD

**Issue by rpieroni** [nomiddlename/log4js-node#177]
I need to create a log file dynamically (one per user session).

I found that I could do that quite easily by using the addAppender method. Using the session id as the logger name and the log filename.

When the user logs out, I would like to remove the logger/appender in order to prevent a memory leak.

**Comment by kthakar1990** [comment]
hey @rpieroni , I know this is an old thread, but did you figure out the way to dynamically create log file per user session without memory leak?

if yes can you help me with some code example?

Thanks.
