### ISSUE TITLE
connect-logger sometimes assigns wrong level (color)

### ISSUE THREAD

**Issue by Ognian** [nomiddlename/log4js-node#182]
Hi,
any idea why this happens? looks like a concurrency issue. 
Look at the following output:

```
[2014-02-14 10:59:34.663] (4) [ERROR] limsSrv - 127.0.0.1 - - "GET /src/limsart/Laborarbeiten.png HTTP/1.1" 304 - "http://localhost:3000
```

This should be a WARNING and not an ERROR; Taking into account that such errors occur rarely it looks like the decision if it is a WARNING or an ERROR is somehow taken too early...

**Comment by nomiddlename** [comment]
Closing this. If it is still a problem, please re-open.
