### ISSUE TITLE
multiprocess appender with cluster crash

### ISSUE THREAD

**Issue by colmaengus** [nomiddlename/log4js-node#188]
Hi,

I'm using node cluster to run an express cluster and trying to get log4js multiprocess appender.
Its working fine except that when one of the worker dies it brings down the whole cluster due to an unhandled ECONNRESET error in the socket used by the multiprocess appender.

I can fix the problem by adding an error handler to log4js multiprocess.js but I'm not sure if this the correct thing to do.

Any suggestions ?

Regards

Colm A

**Comment by nomiddlename** [comment]
closing this because the underlying problem was solved.
