### ISSUE TITLE
console.log doesn't respect the logLevel

### ISSUE THREAD

**Issue by riggerthegeek** [nomiddlename/log4js-node#197]
Hi there

I'm using log4js v0.6.13 installed via npm...

Have set up my logger with the log level as "FATAL" and with replaceConsole as true.  When I put in a console.log, the CLI outputs `[INFO] console - message`

Can console messages be suppressed?

Config below...

    log4js.configure({
        appenders: [
            {
                type: "console"
            }
        ],
        replaceConsole: true
    });

    var logger = log4js.getLogger();
    logger.setLevel("FATAL");

    logger.warn("message"); // nothing is output
    console.log("message"); // [INFO] console - message

**Comment by turengege** [comment]
+1

**Comment by nomiddlename** [comment]
`getLogger` returns a new instance, but `getLogger('console')` will return the instance used for console messages - which you can then set the level on. Only two years too late to help, though. Sorry.
