### ISSUE TITLE
DateFile appender unable to create folder

### ISSUE THREAD

**Issue by alexyma** [nomiddlename/log4js-node#207]
I would like to create daily log files in a daily folder and define a pattern like this
"pattern": "\yyyyMMdd\logfile

Log4js failed to write if the directory doesn't exist. I need to write other code to create the folder ahead of time. 

Will Log4js be able to handle creation of folder if it doesn't exist?

**Comment by nomiddlename** [comment]
File appenders are able to create missing directories now. Please re-open if this is still a problem.
