### ISSUE TITLE
file appender with loglevel filter crushes with cluster. 

### ISSUE THREAD

**Issue by shaheenmasood** [nomiddlename/log4js-node#208]
I am using file type appender with loglevel filter in a node.js application with cluster. it works fine under moderate load. But when I increase the load and concurrency (using 'ab'), it fails while trying to write logs. I am guessing I should use 'clustered' appender. I searched a lot on the net but could not find an example on how to define the appender in a json configuration file and how to use it with cluster in .js file. Could you please provide a complete example? Will clustered appender work with loglevel filter? I would like to be able to change log level dynamically.  Thanks.

**Comment by nomiddlename** [comment]
Closing this because most of the problems seem to have been fixed.
