### ISSUE TITLE
'Maximum call stack size exceeded' when logging from "UncaughtException" handler

### ISSUE THREAD

**Issue by guss77** [nomiddlename/log4js-node#210]
Whenever my app has an uncaught exception, the main JS file catches it using `process.on("UncaughtException",handler)`, where the handler tries to use log4js to log the exception and stack trace.

Instead of getting the expected result, I always get this in the node stderr instead:

```
<appdir>\node_modules\log4js\lib\date_format.js:58
    .replace(/y{1,4}/g, vYear)
     ^
RangeError: Maximum call stack size exceeded
```

It seems like date_format throws an uncaught exception, which throws the app into a loop until the stack is exhausted.

**Comment by nomiddlename** [comment]
Fixed a while ago.
