### ISSUE TITLE
Best practice in dependent modules that use log4js

### ISSUE THREAD

**Issue by mradamlacey** [nomiddlename/log4js-node#212]
I'm looking for some advice or best practices on how to use a node module that uses log4js without stepping on a log4js configuration in the parent applicaiton.

E.g. my app uses log4js to log things (and during its startup calls `configure`).

I require another module (that I don't own) that also uses `log4js` and it also might call `configure` which  removes any previous configured appenders and of course breaks logging for my app.

Are there any approaches to insulate my app from any dependent modules usage of log4js?  Or best practices that the dependent modules should use so they play nicely (call `addAppender` instead of `configure`?)

**Comment by nomiddlename** [comment]
This is now supported by using [log4js-api](https://www.npmjs.com/package/@log4js-node/log4js-api) in third-party modules.
