### ISSUE TITLE
Corrupts log items

### ISSUE THREAD

**Issue by destitutus** [nomiddlename/log4js-node#213]
https://github.com/nomiddlename/log4js-node/blob/v0.6.15/lib/appenders/loggly.js#L37

We have enabled log4js and loggy appender and it corrupt our arguments.
we run it with same params function1([1,2,3], {})
and in trace it looks like as

it can be related with call log4js.trace(1,2,3)

``` js
2014-07-03 09:34:14.195] [TRACE] command { '0':
   [ { level: 'TRACE', category: 'cat', hostname: 'hostname' },
     { level: 'TRACE', category: 'cat', hostname: 'hostname' },
     1,
     2,
     3],
  '1':
   {}]
```

**Comment by nomiddlename** [comment]
Fixed by #232
