### ISSUE TITLE
'alwaysIncludePattern' is important when multiple process write to one log file.

### ISSUE THREAD

**Issue by shaolianbo** [nomiddlename/log4js-node#218]
When I ignore 'alwaysIncludePattern' and use log4js in my multiple process application, the 
log rolling is bad, you can see, the old log is stilll being writen.   So, I spend  sometime read the source code. Now , I know it is due to the time when tow process write to log file is different.  And   'alwaysIncludePattern' can change the way the log roll.
I hope the author can  underline 'alwaysIncludePattern' in wiki .

**Comment by nomiddlename** [comment]
Multiple processes writing to the same file will have all sorts of problems, this isn't recommended (and I don't think using `alwaysIncludePattern` will make any difference to that). 

Sorry for the extremely late reply, just doing some old issue clean up.
