### ISSUE TITLE
How does "replaceConsole":true work? 

### ISSUE THREAD

**Issue by SHARMASH** [nomiddlename/log4js-node#247]
# Here is my log4js.json file:

{
  "appenders":       

  [
    {"type": "console"},
    { 
      "category": "ASM",
      "type": "file",
      "absolute":true, 
      "filename": "~/tomcat/logs/mylog.log", 
      "maxLogSize":2048,
      "layout": { 
        "type": "pattern",
        "pattern" : "%d|%-5p|%c{1} %m%n"
      } 
    }
  ],

```
"replaceConsole":true
```

}

I am unable to get the console.log() messages to be automatically redirected to ~/tomcat/logs/mylog.log. What am I doing wrong?

**Comment by nomiddlename** [comment]
Closing this as the user never provided more information.
