### ISSUE TITLE
logger.setLevel() has inconsistent effect

### ISSUE THREAD

**Issue by ravi** [nomiddlename/log4js-node#248]
Calling logger.setLevel() after calling configure() and getLogger() has inconsistent behaviour. If the configure object/file passed to configure() has level set to X for an appender (assume for simplicity that there is only one appender), then setLevel(Y) has the desired effect only if level Y is more restrictive/selective than X. So if a configuration specifies the file appender and sets level to INFO, then setLevel('DEBUG') has no effect. Whereas setLevel('WARN') reduces the logs to WARN entries.

In the environment in which I notice the issue, I am using Cluster and the multiprocess appender.

**Comment by nomiddlename** [comment]
Sorry for totally ignoring this - I don't know what happened, but it was very rude of me. 

The way loggers, levels and the log level filter work has been changed in v2, so I don't think this problem still exists. But if you're using log level filter and want to be able to change the levels that it allows through, then you would have to call `log4js.shutdown` and then re-configure.

Once again, sorry for having missed this issue and thank you for your kind offer of a PR.

**Comment by ravi** [comment]
@nomiddlename no worries, thank you for the response.
