### ISSUE TITLE
How can specify filename: "$LOG_DIR/mylogs/mylog.log" in the log4js.json file so that it can be resolved based on what is $LOG_DIR set to?

### ISSUE THREAD

**Issue by SHARMASH** [nomiddlename/log4js-node#249]

**Comment by nomiddlename** [comment]
Use the object-style configuration, and replace `'$LOG_DIR/mylogs/mylog.log'` with `process.env('LOG_DIR')+'/mylogs/mylog.log'`.

(Sorry for the extremely late reply - I'm doing some issue cleanup)

**Comment by nomiddlename** [comment]
You could pre-process your json file using a module like [template-resolver](https://www.npmjs.com/package/template-resolver), and then pass the object to log4js.
