### ISSUE TITLE
dateFile should support max log count

### ISSUE THREAD

**Issue by jsha** [nomiddlename/log4js-node#251]
Similar to the `backups` option for the `file` appender, it would be great to explicitly configure `dateFile` to remove logs in excess of N backups. The docs specify that you can do this by creating a pattern such that the pattern wraps around at e.g. 1 month. But I'd like to be able to name my logs like 2014-10-03 and still have old ones deleted weekly.

**Comment by yunnysunny** [comment]
i can't agree with you more

**Comment by purple-panda** [comment]
+1

**Comment by jssoscar** [comment]
+1

**Comment by twoeo** [comment]
+1

**Comment by nomiddlename** [comment]
Date file has a `daysToKeep` option now.
