### ISSUE TITLE
Change the level colors

### ISSUE THREAD

**Issue by omer727** [nomiddlename/log4js-node#254]
Hi,
I want to change the colors of the colored layout.
More specifically I want to make the info log level white and not green.
How can I do that without overriding the log4js library or too many monkey patching?

**Comment by ms270169** [comment]
@nomiddlename, writing my own layout is like inventing new the wheel. Your layouts are fine and have all functionality I need. Like omer727, I only miss the possibility to change colors.

A view modifications in [layouts.js](https://github.com/nomiddlename/log4js-node/blob/master/lib/layouts.js) would offer this feature. Maybe you add some export funtions to set the [colours](https://github.com/nomiddlename/log4js-node/blob/master/lib/layouts.js#L18) and [styles](https://github.com/nomiddlename/log4js-node/blob/master/lib/layouts.js#L57) objects, to have the opportunity to customize the used color-scheme.
Or you add a config parameter for colors to function [patternLayout()](https://github.com/nomiddlename/log4js-node/blob/master/lib/layouts.js#L171) and function [colouredLayout()](https://github.com/nomiddlename/log4js-node/blob/master/lib/layouts.js#L123).

That's it.

**Comment by nomiddlename** [comment]
@ms270169 that's a fair point, I'll see if I can get something working for the next big version release.

**Comment by nomiddlename** [comment]
Released in version 2.0.0
