### ISSUE TITLE
Make it possible to append a configuration without clearing out the existing configuration.

### ISSUE THREAD

**Issue by bolinfest** [nomiddlename/log4js-node#259]
If multiple node modules require the same instance of `log4js.js` and each calls `configure()`, then only the last configuration will win because `configure()` eventually calls `clearAppenders()`. This is an issue in [Atom](https://discuss.atom.io/t/recommended-approach-to-logging/13003/5).

If there were an `appendConfiguration()` API that everyone were encouraged to use instead of `configure()`, then I think this would address the issue.

**Comment by nomiddlename** [comment]
This would be fixed now by libraries using [log4js-api](https://www.npmjs.com/package/@log4js-node/log4js-api).
