### ISSUE TITLE
How to use with Browserify?

### ISSUE THREAD

**Issue by martinhbramwell** [nomiddlename/log4js-node#263]
Hi

The issue "Browserify support #152" suggests it is possible to browserify log4js.  When I try to do it, however, my client-side script fails at the moment of requiring log4js.

It cannot find an appender to use.  In fact, I can see that no appenders are included in the bundle.

Am I trying something that cannot be done?  If it is possible, where can I find a working example?

Thanks.

**Comment by nomiddlename** [comment]
Fixed by PR #264
