### ISSUE TITLE
Datefile and file appenders add blank lines on shutdown

### ISSUE THREAD

**Issue by abellina** [nomiddlename/log4js-node#270]
Hello

When I shutdown log4js using log4js.shutdown, the shutdown function gets called in the configured dateFile appender (this function also would get called in the regular non-sync file appender).

Shutdown tests the stream by attempting to write a new line. I think this should be changed to instead write an empty string ('') such that the logs don't end up with an extra white line written to file.

Thoughts? 

```
function shutdown(cb) {
  async.each(openFiles, function(file, done) {
    if (!file.write(eol, "utf-8")) { /// -> change this to !file.write ('', "utf-8")
      file.once('drain', function() {
        file.end(done);
      });
    } else {
      file.end(done);
    }
  }, cb);
}
```

**Comment by armandciejak** [comment]
Your "patch" used to work with version 0.6.21 but since I upgraded to 1.1.0 it doesn't work anymore: the  process is stuck forever when calling the shutdown function.

**Comment by armandciejak** [comment]
The problem comes from the streamroller module which doesn't implement the end method in version 0.2.x. Everything is working as before when updating streamroller to version 0.3.x.

**Comment by nomiddlename** [comment]
Yep, the code in master uses streamroller 0.3.x because of that issue - so this problem will be fixed in the 2.x release. In the meantime, manually installing streamroller 0.3 would be a good workaround, as you say.

**Comment by nomiddlename** [comment]
I'll also add in the change to write an empty string instead of a new line.
