### ISSUE TITLE
some log writen by dataFile may miss when use cluster

### ISSUE THREAD

**Issue by yunnysunny** [nomiddlename/log4js-node#274]
The configuration of log4js i used curently:

``` javascript
log4js.configure({
    appenders: [
        { type: 'console' },
        { type: 'dateFile',filename:debugFile,'pattern':'-yyyy-MM-dd',category: 'debug'}, 
        { type: 'dateFile',filename:traceFile,'pattern':'-yyyy-MM-dd',category: 'trace'},
        { type: 'file',filename:errorFile,maxLogSize:102400000,backups:10,category: 'error'}
    ],
    replaceConsole : true
});
```

When i used single process,everything ran ok. But when i used cluster (with multi-process), i found some logs missed in `dataFile`.For example , it wrote http access log into both `console` and `trace` file, but i found some http access log only existed in `console` log file.The same thing  happened between the log of `debug`  and `console`.
The version of log4j i used now is 0.6.21.

**Comment by nomiddlename** [comment]
Sorry for missing this issue - the fix for the version of log4js you were using was to use the `cluster` appender. In version 2.x cluster support is transparent.
