### ISSUE TITLE
change filename after configure

### ISSUE THREAD

**Issue by rndmania** [nomiddlename/log4js-node#275]
i want logging to separated file per process

at master process
 call log4js.configure('./conf/log4js.json');

and then each worker processes
 do something for change filename
example : log4js.getLogger('category').??

how can i do it?

**Comment by nomiddlename** [comment]
```javascript
if (cluster.isMaster) {
  log4js.configure(masterConfig);
} else {
  log4js.configure(workerConfig);
}
```
