### ISSUE TITLE
Is there a way to add a custom log level?

### ISSUE THREAD

**Issue by psnider** [nomiddlename/log4js-node#276]
I'd like to be able to add a special log level, called sensitive, 
used for logging anything that must never be logged by a production system.
This would solve two problems for me:
- It would allow me to use logs to debug code paths that operate on sensitive data
- It would tag those code locations that use sensitive data

Is there a way to do this?
I searched the docs and code, but it appears this isn't supported.

**Comment by psnider** [comment]
log4j 2 supports the functionality that I'm looking for:
http://logging.apache.org/log4j/2.x/manual/customloglevels.html
an example from this web page is:

```
final Logger logger = LogManager.getLogger();
// Create and use a new custom level "DIAG".
logger.log(Level.forName("DIAG", 350), "a diagnostic message");
// Use (don't create) the "DIAG" custom level.
// Only do this *after* the custom level is created!
logger.log(Level.getLevel("DIAG"), "another diagnostic message");
```

While log4j 2 does not support adding the convenience log method *diag*, I think it would be easy in javascript.

**Comment by lpaulger** [comment]
I'll jump on his train as well.  At least in my case, some of the developers want to use the same levels [available in log4net ](http://stackoverflow.com/questions/2675710/using-other-log4net-logging-levels-than-the-usual-ones)

I noticed that in lib/levels.js is where these levels are created. Perhaps If I put together a smart way for this to be configurable, I could try to submit those as a potential pull request?

**Comment by nomiddlename** [comment]
Happy to see a pull request for this, if you want to submit one. Remember the rules, though: I'm a stickler for unit tests.

**Comment by nomiddlename** [comment]
Custom log levels are fully supported in version 2.x

**Comment by jchuai** [comment]
Is there any doc or example about custom log level? I didn't see anything about this in the latest version 2.2.0

**Comment by vphantom** [comment]
@jchuai Back when I used v0.6.38, from looking at `docs/api.md` and playing around I defined the levels I needed (something closer to standard syslog) with `levels`:

```js
log4js.levels.forName('NOTICE', log4js.levels.INFO.level + 1);
log4js.levels.forName('WARNING', log4js.levels.WARN.level + 1);
log4js.levels.forName('CRITICAL', log4js.levels.ERROR.level + 1);
log4js.levels.forName('ALERT', log4js.levels.ERROR.level + 2);
log4js.levels.forName('EMERGENCY', log4js.levels.ERROR.level + 3);
```

…and I defined several appenders which start at different levels.  (My `main.log` starts at "info", `errors.log` starts at "error", another `access.log` is only sensitive to category "http", etc.)

This may have changed in 2.x; I haven't played with it this year yet.

**Comment by nomiddlename** [comment]
Take a look at [the API docs](https://nomiddlename.github.io/log4js-node/api.html) - there's a `levels` field you can specify in your configuration. As an example:
```javascript
log4js.configure({
  levels: {
    NOTICE: { value: 20001, colour: 'green' }
  },
  appenders: { out: { type: 'stdout' } },
  categories: { default: { appenders: ['out'], level: 'NOTICE' } }
});
```

**Comment by paulhocker** [comment]
+1 this works like a dream!

**Comment by jlwagoner-bayer** [comment]
i've successfully figured out how to add a custom log level, but am a little stuck figuring out how to use it. for example, my custom log level is called "NOTIFY" but how should I go about setting up a custom method on the logger to be able to call logger.notify(message)?

**Comment by lamweili** [comment]
@jlwagoner-bayer, if you have configured it through `log4js.configure()`, you should be able to use `logger.<level>()` where level is lowercased.

**Comment by lamweili** [comment]
@jlwagoner-bayer, if you have configured it through `log4js.configure()`, you should be able to use `logger.<level>()` where the level is lowercased.

```js
var log4js = require('log4js');
log4js.configure({
  levels: {
    NOTICE: { value: 20001, colour: 'green' }
  },
  appenders: { out: { type: 'stdout' } },
  categories: { default: { appenders: ['out'], level: 'NOTICE' } }
});

var logger = log4js.getLogger();
logger.notice('hello world');

// [2022-09-13T09:53:00.790] [NOTICE] default - hello world
```

**Comment by lamweili** [comment]
@jlwagoner-bayer, if you have configured it through `log4js.configure()`, you should be able to use `logger.<level>()` where the level is lowercased.

```js
var log4js = require('log4js');
log4js.configure({
  levels: {
    NOTICE: { value: 20001, colour: 'green' }
  },
  appenders: { out: { type: 'stdout' } },
  categories: { default: { appenders: ['out'], level: 'NOTICE' } }
});

var logger = log4js.getLogger();
logger.notice('hello world');

// [2022-09-13T09:53:00.790] [NOTICE] default - hello world
```
