### ISSUE TITLE
Calling logger.log is dangerous

### ISSUE THREAD

**Issue by deltaflux** [nomiddlename/log4js-node#279]
I've seen people accidentally call logger.log instead of logger.info (especially when converting console.log calls) which generally throws an exception because it expects a level as the first argument. 

Issue #272 looks like someone who has fallen over exactly this problem.

Is it an intentional part of the API or would it be okay to modify the library to hide the logger.log method? I didn't want to make a pull request if it's not going to get pulled :)

If it is intentionally exposed it should at least be cleared documented and would ideally throw a more explanatory exception if misused.

**Comment by nomiddlename** [comment]
It might be better to check if the first argument is a level, if not then default to INFO - that way no exception gets thrown, and any existing code that calls logger.log correctly won't break.

**Comment by nomiddlename** [comment]
Fixed in 0.6.23
