### ISSUE TITLE
Do we have a function like `getLoggers`?

### ISSUE THREAD

**Issue by dayuoba** [nomiddlename/log4js-node#283]
After using 
```
log4js.configure(appenders);
```
How can i get one Object with all loggers registered?
like 
```
var loggers = log4js.getLoggers();
//or some other function?
```

**Comment by nomiddlename** [comment]
There isn't a way to do that currently. Could you explain why you'd need to do it?

**Comment by dayuoba** [comment]
I want in my project that the app.utils.loggers can be used in different places or ways.
eg:
```
app.utils.loggers.appLogger.info()
```
some where maybe:
```
app.utils.loggers.serverLogger.error()
```
So i want a function can return the loggers registered
just like `app.utils.loggers = log4js.getLoggers();`

**Comment by nomiddlename** [comment]
I realise this is a year late, but you could define your logger instances yourself. e.g. `app.utils.loggers.serverLogger = log4js.getLogger("server")`
