### ISSUE TITLE
How can I hold the Default Configuration Informantion of log4js

### ISSUE THREAD

**Issue by jacktan1991** [nomiddlename/log4js-node#284]
Calling `log4js.configure(...);` is something like `setter` method, which will change the default or previous configuration of log4js. How can I hold the previous configuration of log4js? I want reuse those configuration informantion after calling this setter-style method. 

Does it provide **getter-style** method?

**Comment by nomiddlename** [comment]
To do this, I would use the object-style of configuration for log4js and keep a copy of the object for later reuse. log4js doesn't provide a way to inspect the current configuration.
