### ISSUE TITLE
kafka appender support?

### ISSUE THREAD

**Issue by tungv** [nomiddlename/log4js-node#285]
Apache Kafka is a good model for event logging. It's so helpful to have kafka support built-in in log4js.
(Or it's there and I'm missing something?)

What do you guys think?

**Comment by nomiddlename** [comment]
If someone wants to write an appender, I'm happy to look at pull requests.

**Comment by nomiddlename** [comment]
Closing this one - two years and nobody provided an appender.

**Comment by sadapasta** [comment]
Hello?  is someone writing the Kafka appender ?
