### ISSUE TITLE
smtp appender is not working with the current version of nodemailer

### ISSUE THREAD

**Issue by alawatthe** [nomiddlename/log4js-node#287]
Here is the [migration guide](https://andrisreinman.com/nodemailer-v1-0/#migrationguide).

I patched this problem for my use and I hope, that I have time in the next few days to create a pull request.

Before doing this however, I have a minor question: Is there a way to use different log levels for different appenders? I.e. I want to log all levels into a file but only send mails on ```WARN```, ```ERROR``` and ```FATAL```.
If not, that would be great to have :-D

**Comment by nomiddlename** [comment]
You can wrap your mail appender in a log level filter - there's a couple of examples in the source.

**Comment by alawatthe** [comment]
Thanks for the hint with the log level filter. I think this needs better/more visible documentation, e.g. its own wikipage.

I created a pull request #288 for the nodemailer migration.
