### ISSUE TITLE
Syslog sees everything as INFO

### ISSUE THREAD

**Issue by vanga** [nomiddlename/log4js-node#302]
please refer this http://stackoverflow.com/questions/30703452/correct-log-levels-are-not-being-sent-to-read-by-syslog-from-a-systemd-service

Summary:
I am on ArchLinux, using syslog-ng.
Syslog sees all log events as INFO level. How ever, If I start the server as `bin/server` console shows log events in different colours. Also If I see the logs in `/var/log/everything.log` (log events logged by syslog to this file) they have ANSI color codes. 

Above observations make me think that log4js is sending the color information, but not actually setting the Log level.

This is my log4j config  (in Coffee)
```
log4js.configure appenders: [
    { type: "console" }
  ]
```
Is it possible to set the Log levels also? do I have to set something in log4js config?

Thanks.

**Comment by nomiddlename** [comment]
I don't know anything about how syslog-ng determines log levels - is it pattern matching on the output or something? It may be the colour codes are confusing it. By default the console appender outputs the ansi colour codes, but you can turn that off by using `{ type: "console", layout: { type: "basic" } }`.

If it isn't that, then maybe you'll need to use the pattern layout to make your log output conform to whatever it is syslog-ng needs.

**Comment by vanga** [comment]
@nomiddlename thanks.
w.r.t log4js-node, is the colour information the only thing that is being sent along with the log event that tells about it's log level? do we say a log has a particular log level based on the colour code information?

In the Readme section of this repo,
> different log levels for different log categories (make some parts of your app log as DEBUG, others only ERRORS, etc.)
Does this mean that log4js-node sends a particular colour code if its `logger.debug("hello")`, does it do any thing more?

I believe some meta data information along with the log event has to be sent for the syslog to understand the levels, I am not sure though.

I came across this https://github.com/schamane/node-syslog , syslog is able to understand the log levels from this.

May be what I need is a separate appender for syslog I guess?

**Comment by vanga** [comment]
I just did some reading, Yes, messages need to be logged using syslog protocol http://www.syslog.cc/ietf/drafts/draft-ietf-syslog-protocol-03.html#format

this must be the reason for syslog being not able to understand the log levels from log4js.
