### ISSUE TITLE
INFO level filter do nothing

### ISSUE THREAD

**Issue by klimashkin** [nomiddlename/log4js-node#303]
Hello!
With such log config:
```
{
    "replaceConsole": true,
    "levels": {
        "[all]": "INFO"
    },
    "appenders": [
        { "type": "console" }
    ]
}
```
I see in console also [TRACE] and [DEBUG] messages
But if I set level to ```"[all]": "WARN"``` console output become without TRACE, DEBUG and INFO, as expected

**Comment by nomiddlename** [comment]
With the following test code, I see only the INFO and ERROR messages. 
```javascript
var log4js = require('../lib/log4js');
log4js.configure({
	replaceConsole: true,
	levels: {
		"[all]": "INFO"
	},
	appenders: [
		{ type: "console" }
	]
});

console.debug("I should not see this.");
console.info("I should see this.");
console.error("I should also see this.");
```

Is your code doing something different?

**Comment by bcowgill** [comment]
I noticed this problem too. Here is an example.

var log4js = require('log4js'), log = log4js.getLogger();
log4js.configure({
    replaceConsole: true,
    levels: {
        "[all]": "INFO"
    },
    appenders: [
        { type: "console" }
    ]
});

log.setLevel("ERROR");

console.debug("debug I should not see this.");
console.info("info I should not see this.");
console.log("log I should not see this.");
console.warn("warn I should not see this.");
console.error("error I should see this.");

produces 
[2015-10-11 01:46:08.608] [INFO] console - info I should not see this.
[2015-10-11 01:46:08.611] [INFO] console - log I should not see this.
[2015-10-11 01:46:08.611] [WARN] console - warn I should not see this.
[2015-10-11 01:46:08.612] [ERROR] console - error I should see this.

It only seems to work if ERROR is configured in the config file, not when switched with setLevel

**Comment by nomiddlename** [comment]
Ah, this is a problem with the console appender using a specific logger called 'console'. If you were to do this instead `log4js.getLogger("console").setLevel("ERROR")`, it would behave as you expect. And it's only taken me a year to work it out.
