### ISSUE TITLE
Multiple 'type'

### ISSUE THREAD

**Issue by huntonas** [nomiddlename/log4js-node#309]
I tried having multiple 'type' on a appender, but it doesn't seem to be working. Is there a way to have categoryFilter and logLevelFilter on one appender? Thanks.

**Comment by huntonas** [comment]
Wondering if you got a chance to look into this. Thank you

**Comment by nomiddlename** [comment]
I've not tried it, but you should just be able to nest the filters. Wrap the categoryFilter around the logLevelFilter, the same way as the logLevelFilter wraps the base appender.

**Comment by huntonas** [comment]
That worked. Just for documentation purposes, this is how I did it.
```
type: 'categoryFilter',
      exclude: 'connect',
      appender: {
        type: 'logLevelFilter',
        level: webLogLevel,
        appender: {
          type: 'dateFile',
          filename: logDir + 'name',
          pattern: '-yyyy-MM-dd',
          layout: {
            type: 'pattern',
            pattern: logPattern
          }
        }
      }
