### ISSUE TITLE
require exceptions are silenced

### ISSUE THREAD

**Issue by arty-name** [nomiddlename/log4js-node#311]
[`requireAppender` function silences all error messages from `require`](https://github.com/nomiddlename/log4js-node/blob/master/lib/log4js.js#L388) and that leads to difficult debugging. I just had `semver` package missing due to [npm bug](https://github.com/npm/npm/issues/4161), and that prevented `file` appender from loading and resulted in extra cryptic error. Please do not silence exceptions.

**Comment by nomiddlename** [comment]
Fixed in version 2.x - requiring appenders explicitly checks if the error was "MODULE_NOT_FOUND".
