### ISSUE TITLE
log4js.fileAppender - Writing to file ../logfile/2015-7-10.log, error happened  

### ISSUE THREAD

**Issue by Messilimeng** [nomiddlename/log4js-node#314]
error in  linux

{ [Error: ENOENT, open '../logfile/2015-7-10.log'] errno: -2, code: 'ENOENT', path: '../logfile/2015-7-10.log' }

**Comment by nomiddlename** [comment]
You're going to have to give me a bit more to work with here. What does your log4js config look like? Does the "logfile" directory exist? log4js won't create directories.

**Comment by Messilimeng** [comment]
log4js config 


var log4js = require('log4js');

log4js.configure({
	appenders: [{
		type: 'console'
	}, {
		type: 'file',
		filename: '../logfile/'+ new Date().getFullYear() + "-"+ (new Date().getMonth()+ 1) + "-"+ new Date().getDate()+'.log',
		category: 'cheese'
	}]
});

module.exports.logger = log4js.getLogger('cheese');

**Comment by nomiddlename** [comment]
Closing this - assuming that the user managed to get it to work.

**Comment by Trueg112** [comment]
How can i use this on backbone.js with require.js ? I'm tried but is not working. Can you please help me out this!

**Comment by ciglesiasweb** [comment]
I have the same problem on my EC2 instance:

 log4js.fileAppender - Writing to file /home/........../logs/app.log, error happened  { Error: EACCES: permission denied, open '/home/..........//logs/app.log'
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/home/..........//logs/app.log'
