### ISSUE TITLE
Configurable rolling log file name

### ISSUE THREAD

**Issue by viddeshshinde** [nomiddlename/log4js-node#319]
I am using log4js to log in my node js application. I have configured logger to create a log file when the file size reaches certain max size. The logger creates a file with same filename and '.' and index number is appended to the file name where index number is incremented every time a new file is created.

I use current timestamp when file is created in the filename as: 20150730060112.log then next files created are as 20150730060112.log.1, 20150730060112.log.2 20150730060112.log.3 and so on...

I want a next file to be created with current timestamp. For e.g. if 20150730060112.log file reaches maxLogSize at lets say on 2015-07-31at 07:04:13  then the filename of new file I want to be as 20150731070413.log. 

Please let me know if this is possible or any work around to get to this.

**Comment by nomiddlename** [comment]
This is not possible with the current implementation, and I can't think of any workarounds. Closing this one, but feel free to re-open if you think this is still important.

**Comment by viddeshshinde** [comment]
Hello, I have implemented this locally by doing some customisation in log4js module code. Is it fine if I upload my own module over npm.

**Comment by nomiddlename** [comment]
Would this module be an appender that could be used with log4js, or would someone have to replace log4js with your module instead? 

There's no problem with you uploading your own module either way - log4js is licensed under Apache 2.0 so you're free to do that. However, if the module is a replacement for log4js, then please make that clear to your users and also make it clear that users of your module should not raise any issues with log4js - I don't want any confusion. If your module is just an appender that can be used with log4js, then there's no problem - go for it!

**Comment by viddeshshinde** [comment]
Well its not an appender, one will have to use as a whole. Don't worry, I will take care so that there will be no confusion with log4js module.
