### ISSUE TITLE
use json file to configure log4js does not work

### ISSUE THREAD

**Issue by baolinCloud** [nomiddlename/log4js-node#321]
![image](https://cloud.githubusercontent.com/assets/10859771/9987250/91a9218e-6078-11e5-85d4-23d6f35873e2.png)

I create a json file logConf.json , the content is below:

{
    "appenders": [
        {
        "type": "file",
        "absolute": true,
        "filename": "test/test.log",
        "maxLogSize": 40960000,
        "backups": 30,
        "category": "absolute-logger"
    }],
    "levels": {
      "[all]": "INFO"
    }
}

-----------------

 Then i create a testLog.js , configure log4js 

var log4js = require('log4js');
log4js.configure('logConf.json');

var logger = log4js.getLogger('entry');
logger.info('hahah');

----------------

node testLog.js, nothing happened；

---------------
when i configure in testLog.js,
log4js.configure({
    appenders: [
        {
        type: 'file',
        filename: __dirname + '/test.log',
        maxLogSize: 40960000,
        backups: 30
    }],
    'levels': {
      '[all]': 'INFO'
    }
});

it works!

----------------

So use json file to configure log4js does not work ???

or something error with my test?

**Comment by nomiddlename** [comment]
In your `logConf.json` you've given the appender a category of `absolute-logger`. This means that only log messages that use a logger called `absolute-logger` will get sent to that appender. In your `testLog.js` file, you're using a logger called `entry`, so nothing gets logged. In the second example where you're configuring log4js in your code, you haven't applied a category to your appender, so it logs everything.

**Comment by baolinCloud** [comment]
Get it ! Thanks!
