### ISSUE TITLE
How can I control how many days are rolled in 'dateFile' appender with the default '-yyyy-MM-dd' pattern?

### ISSUE THREAD

**Issue by TascSystems** [nomiddlename/log4js-node#323]
Is there an option to control the maximum number days to roll?

At first I thought this was controlled by the "backups" option, but a quick look at RollingFileStream.js seems to indicate that this manages indexes, not necessarily related to the date rolling pattern.

I'm new to log4js - if I can help on this issue, let me know.

(I also posted this on StackOverflow)

**Comment by nomiddlename** [comment]
Sorry, this isn't possible right now - backups only applies to RollingFileStream, you're right. It does sound like a reasonable addition, though.

**Comment by TascSystems** [comment]
Gareth, if you give me some hints on how to do it, I will because I need this for an embedded project, I can't have more than a months worth of files on the flash.

**Comment by nomiddlename** [comment]
I think you'd have to keep an array of the rolled files in memory, capped to the number of backups, adding entries as you roll and removing ones from the end of the list when the array is full. You'd also have to examine the log directory on startup to populate the list with existing files. It might be easier to set up a cron job to delete files older than a certain amount - but I guess that might not be possible in an embedded environment.

**Comment by TascSystems** [comment]
I'll probably get back to this as I complete other stuff - probably in a month or two. I'll give you the code once I'm done.

**Comment by ea7son** [comment]
are you done ?

**Comment by andreipak** [comment]
Any updates?

**Comment by twoeo** [comment]
Any updates?

**Comment by nomiddlename** [comment]
Date file appender now has a `daysToKeep` option (or at least, the underlying streamroller library has). Just add that option to your dateFile config and it should work.
