### ISSUE TITLE
trace broken in Firefox

### ISSUE THREAD

**Issue by fholzer** [nomiddlename/log4js-node#325]
Tested with Firefox 41.0.1, loglevel 1.4.0.
To reproduce, go to https://jsfiddle.net/zLsjmg2d/2/ in Firefox and open console.
Expected result: console should show trace log messages.
Actual result: console shows "console.trace():"

**Comment by nomiddlename** [comment]
You've got the wrong project, mate. I think you want to post this in https://github.com/pimterry/loglevel

**Comment by fholzer** [comment]
You're totally right. Sorry about that. Should manage my open tabs in a better way ;)
