### ISSUE TITLE
console.dir is not being sent to the same location as console.log

### ISSUE THREAD

**Issue by bcowgill** [nomiddlename/log4js-node#327]
With this config.json

{
  "appenders": [
    { "type": "console" }
  ],
  "replaceConsole": true
}

console.log('console.log');
console.dir({'called': 'console.dir'});

gives this output
[2015-10-11 01:29:41.787] [INFO] console - console.log
{ called: 'console.dir' }

was expecting something like
[2015-10-11 01:29:41.787] [INFO] console - console.log
[2015-10-11 01:29:41.787] [INFO] console - { called: 'console.dir' }

**Comment by nomiddlename** [comment]
`console.dir` is not one of the functions that gets replaced - only the ones that map to log levels (debug, error, log).
