### ISSUE TITLE
feature request: support grabbing log4js configuration from the node-config module

### ISSUE THREAD

**Issue by bcowgill** [nomiddlename/log4js-node#328]
It would be great if you supported grabbing your config from the log4js key of the node-config module.

https://github.com/lorenwest/node-config/wiki/Sub-Module-Configuration

I've made a code example which configures from log4js key or specifies a log4js.json file
along with reloadSecs and cwd parameters to allow monitoring of a log config file.
If this was implemented into log4js then you could support monitoring any format config file (yml, etc)
that node-config supports.

For example

config/default.json (but can be yml or a variety of other file formats supported by node-config)
{
    "comment": "default configuration always loaded",
    "log4js": {
        "appenders": [{
            "type": "console",
            "layout": {
                "type": "pattern",
                "pattern": "[%d{ABSOLUTE}] %[%-5p %10c%] - %m"
            }
        }],
        "replaceConsole": true
    }
}

config/production.json
{
  "port": 9000,
  "log4js": {
    "configureFile": {
      "fileName": "config/log4js.json",
      "options": {
        "reloadSecs": 15,
        "cwd": "/tmp/logs"
      }
    }
  }
}

My test program loads this config as follows.

var c = require('config'),
    l = require('log4js');

if (c.has('log4js')) {
    var debug = require('debug')('log4js');
    var l4c = c.get('log4js');
    debug('log4js: config root', l4c);
    if (l4c.has('configureFile')) {
        var cf = l4c.get('configureFile');
        var fileName = cf.get('fileName');
        var options = cf.has('options') ? cf.get('options') : {};
        debug('log4js: load and monitor config json ' + fileName, options);
        l.configure(fileName, options);
    }
    else {
        debug('log4js: configure from config object', l4c);
        l.configure(l4c);
    }
}

node test.js  # will get from the default.json
NODE_ENV=production node test.js  # will get log4js config from production.json

**Comment by nomiddlename** [comment]
Happy to take a pull request for this, if anyone feels like implementing.

**Comment by nomiddlename** [comment]
Closing this one, because nobody did provide a pull request and it's probably pretty easy to write your own wrapper around log4js if you want to.
