### ISSUE TITLE
Enabling configuartion reloading reloads the default configuration multiple times

### ISSUE THREAD

**Issue by efreeti** [nomiddlename/log4js-node#33]
So I have custom config file log4js-config.json

{
	"appenders": [
		{
			"type": "console",
			"layout": {
				"type": "basic"
			}
		},
		{
			"type": "file",
			"filename": "log/application_server.log"
		}
	]
}

This line:

log4js.configure(__dirname + '/log4js-config.json', {
	"reloadSecs": 10
});

Will reload my config on any change but also each 10 seconds reload the default config (overwriting my settings - basic layout instead of colorized one (btw it doesn't work on Windows so you might consider some coloring library))

**Comment by nomiddlename** [comment]
Closing this because it is really old, and nobody has raised the issue since.
