### ISSUE TITLE
Support for console methods 'time & timeEnd'

### ISSUE THREAD

**Issue by balajigumpena** [nomiddlename/log4js-node#337]
I am trying log4js-node for my project. I am using console.time and and console.timeEnd for function execution time on console, i wanted these on log files as well, so i tried logger.time and logger.timeEnd where logger is log4js object, but it threw an error. Please let me know what all the methods of console are overridden when using 'replaceConsole' attribute 

Code snippet :
logger.time("INFO","TimeForCodeRecieve");
logger.timeEnd("INFO","TimeForCodeRecieve");

Exception:
 logger.timeEnd("INFO","TimeForCodeRecieve");
                       ^
TypeError: Object #<Logger> has no method 'timeEnd'

**Comment by Glavin001** [comment]
Looks like it was in the works: https://github.com/nomiddlename/log4js-node/pull/257

**Comment by nomiddlename** [comment]
Console replacement was removed in version 2.x, and the docs updated to make it clear what functions are supported on logger. There is currently no support for 'time' or 'timeEnd'.

**Comment by secreter** [comment]
mark
