### ISSUE TITLE
include "typings" field in package.json

### ISSUE THREAD

**Issue by rolandjitsu** [nomiddlename/log4js-node#339]
Now that the TS compiler supports module [resolution](https://github.com/Microsoft/TypeScript/issues/2338) via node, it would be nice not to use TSD to install the typing but instead have them included with the npm package.

**Comment by lambrojos** [comment]
+1

**Comment by nomiddlename** [comment]
That's a really long conversation to get my head around, especially as I know nothing about Typescript. Is there a summary page? A "what you need to do to your package.json" version of it? If someone who knows more than me wants to submit a PR, I'd be happy to look at it.

**Comment by rolandjitsu** [comment]
@nomiddlename you can take a look at [typings](https://github.com/typings/typings) for seeing how to edit the `package.json`, and the official doc [Typings-for-npm-packages](https://github.com/Microsoft/TypeScript/wiki/Typings-for-npm-packages).

**Comment by a8775** [comment]
+1

**Comment by a8775** [comment]
There is a file close to be ready: 

https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/7554cff7c4dd34decc2f3dc0d711a6c288174eee/log4js/log4js.d.ts

It works for me after stripping all "express" references.
