### ISSUE TITLE
Colouring the whole log?

### ISSUE THREAD

**Issue by Krisa** [nomiddlename/log4js-node#340]
I was wondering whether it would be possible to colour the whole log, instead of just the timestamp and the log level. Also by colouring the whole log, it would be simply possible to remove the log level (since the colour would be enough to identify the level).

**Comment by nomiddlename** [comment]
Patternlayout should be able to do that for you.

Cheers,
Gareth.

**Comment by Krisa** [comment]
Thanks for the hint! Had to dig a bit in the examples, but I found out what I needed. For anyone looking for the same, it's like that:
```javascript
var log4js = require('log4js');

var config = {
	'appenders': [{
		'type': 'console',
		'layout': {
			'type': 'pattern',
			'pattern': '%[%d - %m%n%]'
		}
	}]
};
log4js.configure(config, {});
```
