### ISSUE TITLE
Close and reopen logs on signal

### ISSUE THREAD

**Issue by jsha** [nomiddlename/log4js-node#343]
Systems using `logrotate` need to be able to tell a logging process to close and reopen its logs after it has rotated them, so the process doesn't keep logging to the old inode. Nginx for instance implements this with the -USR1 signal. The file appender in log4js should have a method to close and reopen files, either called from user code or registered as a signal handler.

**Comment by nomiddlename** [comment]
This makes sense. I think most processes listen for the HUP signal. This would only need to be added to the basic file appender, not the RollingFileAppender or DateFileAppender, since I'm assuming that people who configure those appenders wouldn't be using logrotate as well.
