### ISSUE TITLE
Is it possible to have multiple appenders for the same category?

### ISSUE THREAD

**Issue by aledelgo** [nomiddlename/log4js-node#346]
Hello,
I'm used to log4[any-lang] since times and what i mostly liked is the possibility to send the entries of one single logger (or many) to multiple appenders.

Also log4js-connect seemed to have implemented such a feature...
(see: https://github.com/nomiddlename/log4js-connect/blob/master/example.js#L25)

Is it possible also with log4js-node? how?
from config samples it actually seem that category and appender are strictly bound guaranting 1 appender for 1 category...

Thanks

**Comment by nomiddlename** [comment]
log4js-connect was rewritten to use log4js-0.7.x, which I never got around to releasing. The current log4js-node contains the connect logger anyway. 

As far as having multiple appenders for a category, that is possible, as is having multiple categories go to a single appender. Here's an example:
```javascript
log4js.configure({
  appenders: [
    { type: "file", category: [ 'cheese', 'biscuits'], filename: "cats.log" },
    { type: "file", category: [ 'biscuits', 'wine'], filename: "wine.log" }
  ]
});

var cheese = log4js.getLogger("cheese")
, biscuits = log4js.getLogger("biscuits")
, wine = log4js.getLogger("wine");

cheese.info("gouda");
biscuits.info("custard cream");
wine.info("shiraz");
```
You end up with two log files: cats.log contains the cheese and biscuits log statements, wine.log contains the biscuits and wine statements.

**Comment by aledelgo** [comment]
Thanks much! replacing the single category string with an array did the job!

Anyway actually the console appender is completely ignoring the category filter... whatever value i put in, it output in the console all loggers entries. is it normal?
