### ISSUE TITLE
What is the Unit of Measurement of the "maxLogSize" option for an Appender?

### ISSUE THREAD

**Issue by in1gotech-jdjaviniar** [nomiddlename/log4js-node#352]
What is the unit of the option "maxLogSize" below?

```
{
  "appenders": [
    {
      "type": "file",
      "filename": "relative/path/to/log_file.log",

      "maxLogSize": 20480, /* What is the unit of measure of this option? */

      "backups": 3,
      "category": "relative-logger"
    },
    {
      "type": "file",
      "absolute": true,
      "filename": "/absolute/path/to/log_file.log",
      "maxLogSize": 20480,
      "backups": 10,
      "category": "absolute-logger"          
    }
  ]
}
```

**Comment by nomiddlename** [comment]
It is in bytes.

**Comment by in1gotech-jdjaviniar** [comment]
Does it accept 10K, 10M or 10G as valid values?




*John Leonard D. Javiniar*
Jr. Programmer
In1Go Technologies, Inc.

**Comment by nomiddlename** [comment]
No, it doesn't, sorry. I'm happy to accept a pull request that implements that, though.

**Comment by in1gotech-jdjaviniar** [comment]
Oh, sorry to hear that. Does it work on `File `and `DateFIile `appenders alike?

**Comment by nomiddlename** [comment]
Date file appender doesn't use maxLogSize - it rotates logs based on the date, not the size.

**Comment by in1gotech-jdjaviniar** [comment]
Oh I see! I been mixing up the 2 and been scratching my head because of that. My bad.. I'll try check if that is not in the docs and update them if not when I find a free time. Thanks!
