### ISSUE TITLE
Would be nice if there was a categoryFilterOut and a categoryFilterIn style usage

### ISSUE THREAD

**Issue by Smurf-IV** [nomiddlename/log4js-node#353]
Would be even better if it took wildcard(s) for the categories.
i.e. 
base.*
*.smtp

**Comment by nomiddlename** [comment]
Could you explain what you mean a bit more, please?

**Comment by Smurf-IV** [comment]
I'll try.
Imagine you have some sub-directories in a project. (AA, BB, CCC etc)
Each with some files that reflect what a that particular area of code is doing. (AA.aaa, AA.aaa1, etc)
To make the categories "work", so that you do not have to remember to put in the filename for each log line you obtain a logger by doing
getLogger('AA.aaa), so that each log line will have AA.aaa to state what module and file it cam from.
Now in order to get a log file that covers just AA module, then you you would need to have a category for all of the AA.xxxxx file and then exclude all of the other BB.xxx, and CCCC.xxxx etc files.
This lead to a bit of a mess in the log4js config file.
So, I would like to state that the CategoryInFilter to use just 'AA.*' and for it to exclude all others.
And then to compliment this (In case I have root code) to excludeOut everything that is ['AA.*', 'BB.*'](etc)

**Comment by nomiddlename** [comment]
This is possible now (in v2) without changes to the category filter, and indeed without using the category filter. e.g.
```javascript
log4js.configure({
  appenders: { out: { type: 'stdout' } },
  categories: {
    default: { appenders: ['out'], level: 'debug' },
    AA: { appenders: ['out'], level: 'off' }
  }
});
const logger = log4js.getLogger('AA.aaa');
logger.info('I will not get logged.');
```

I'm going to close this one, but feel free to re-open if this doesn't fix your problem.
