### ISSUE TITLE
How do I replace the default console logger?

### ISSUE THREAD

**Issue by peek4y** [nomiddlename/log4js-node#358]
So, I would like to add a new console appender, and replace the default one.

```log4js.addAppender(log4js.appenders.console(<add pattern layout>))```

after adding my new console appender, I see two log messages per call.

How do I disable / replace the existing default console log? Any Example?

**Comment by nomiddlename** [comment]
`addAppender` doesn't clear any existing ones. Calling `configure` will do that though. Try something like:  `log4js.configure({ appenders: [ { type: "console", layout: { type: "pattern", pattern: "something" } }] })`

**Comment by peek4y** [comment]
Ok, so there is no way I can clear from ```addAppender``` ?

**Comment by nomiddlename** [comment]
No. You can call `clearAppenders`, but that will remove all appenders.

**Comment by peek4y** [comment]
Oh ok. thanks :+1:
