### ISSUE TITLE
Is it possible to have different LEVEL for different appenders with same Category?

### ISSUE THREAD

**Issue by peek4y** [nomiddlename/log4js-node#359]
so I've a console appender and a mongo appender, which contains same list of categories, is there a way I can set different levels for different appenders?

**Comment by nomiddlename** [comment]
You probably want to take a look at logLevelFilters and wrap your appenders in them. Take a look at the [example app](https://github.com/nomiddlename/log4js-example) for how to do it.

**Comment by peek4y** [comment]
so how does logLevelFilters work? Does it override other appenders? 

I'm looking for something like, I want console appender, to output at ERROR level and mongo appender to output at DEBUG level.

Appreciate the help!

**Comment by nomiddlename** [comment]
You wrap your appender in a log level filter. The filter can be configured to have both a minimum log level and a maximum level. The filter will only pass log events to the appender that have a level that passes. I'm guessing that currently all log events go to both appenders, but you only want error ones to go to the console. Wrap the definition of the console appender in a log level filter in your config file:
```javascript
{ appenders: [
    { type: "logLevelFilter", 
       level: "ERROR", 
       appender: {
          type: "console"
      }
    },
    {
      type: "mongo",
      ...
    }
]}
```

**Comment by peek4y** [comment]
Ohk, nice :+1:  Thanks for the help!
