### ISSUE TITLE
Auto reload of configuration file - Who does this ?

### ISSUE THREAD

**Issue by Smurf-IV** [nomiddlename/log4js-node#360]
It states in the md file the following

> By default, the configuration file is checked for changes every 60 seconds, and if changed, reloaded. This allows changes to logging levels to occur without restarting the application.

But I cannot see anywhere in the code where this takes place.
i.e. the use of 
`reloadConfiguration` when no options are passed in.
It also inferrs that if options are used, i.e. `{cwd: absoluteLogDir}`, then the reload will still happen. 

have I missed something ?

**Comment by nomiddlename** [comment]
From the code, it looks like reloading the config will only happen if you supply `options.reloadSecs`. The README is lying. I'll fix the README, as I don't think the default behaviour should be to check for changes.

**Comment by Smurf-IV** [comment]
So I have written a Unit test for this and it still does not seem to work as expected.
The following will fail with
**AssertionError: Failed to detect changes to logging without restart !**
after waiting 3 seconds for the logger level to have changed

```
it('Check Log level modification', function (done) {
		this.timeout(4 * 1000);
		var targetFile = path.resolve(__dirname, '../data/story518756.json');
		var configsJson = require(targetFile);
		if (!configsJson) {
			throw new Error('Config file not found: ' + targetFile);
		}
		var utcNow = moment.utc();
		// Now get a "Unix time" 1 hour in the past
		var compStart = utcNow.subtract(1, 'h').unix();
		fs.utimesSync(targetFile, compStart, compStart);    // Set to zero time to allow detection change.
		var testLevel = 'Test';
		const origValue = configsJson.levels[testLevel];
		try {
			assert.ok(origValue, 'Should have been able to get the test value');
			var log4jsTest = require('log4js');
			log4jsTest.configure(targetFile, { reloadSecs: 2 } );
			var testLogger = log4jsTest.getLogger(testLevel);
			assert.equal(testLogger.level, log4jsTest.levels.toLevel(origValue));
			assert.ok(testLogger.isLevelEnabled(origValue));
			configsJson.levels[testLevel] = 'OFF';
			require('fs').writeFileSync(targetFile, JSON.stringify(configsJson, null, 2));

			// Test changes to logging levels to occur without restarting the application.
			setTimeout(function () {
				assert.ok(!testLogger.isLevelEnabled(origValue), 'Failed to detect changes to logging without restart !');
				done();
			}, 3 * 1000);

		} finally {
			configsJson.levels[testLevel] = origValue;
			require('fs').writeFileSync(targetFile, JSON.stringify(configsJson, null, 4));
		}
````

json file contents:
`{
    "appenders": [  { "type": "console" } ],
    "levels": { "Test": "ALL" }
}`

**Comment by Smurf-IV** [comment]
It would be good if the _reload every_ value could also be in the config file

**Comment by Smurf-IV** [comment]
I'm getting the `reloadConfiguration` fired
**But**
The logger levels do not seem to be altered.

Is that expected ?

I Change the value from _Trace _to _Warning _in the file but the logger I retrieved does not change
`{
  "appenders": [ { "type": "console" } ],
  "levels": { "Test": "WARNING" }
}`

This fails after a wait:
`assert.ok(!testLogger.isLevelEnabled(startLevel), 'Failed to detect changes to logging without restart ! ' + startLevel);
`

**Comment by Smurf-IV** [comment]
Darn it !
Found the problem with the above code....
"Test": "**WARNING**"

Warning is not a valid level and "Nothing" was telling me otherwise !

**Comment by nomiddlename** [comment]
Ok to close this issue then?

**Comment by Smurf-IV** [comment]
OK
