### ISSUE TITLE
is there a way to prettify the message part of layout of the log

### ISSUE THREAD

**Issue by e-cloud** [nomiddlename/log4js-node#361]
now the message part is marked as `%m` in the layout pattern.

```
logger.debug(anArray);
logger.debug(anObject);
```

the output is like:

```
[2016-03-15 17:13:44.397] [TRACE] ProgramsLoader - [ 'recipes/qiji.js',
  'recipes/wcg-portal.js' ]
[2016-03-15 17:13:44.398] [DEBUG] ProgramsLoader - { aaaaabbbbbbbbbbaaaaaaaaaa: {}, 
bbbbbbbbbbbbbbbbbbbbbbbb: {} }
```

**the format is broken**

it would be very nice to provide a way to add a newline before outputting an object or array

**Comment by stanleyxu2005** [comment]
You can register your own token. e.g %M and format with a custom function. (I want to strip the trailing spaces with this feature)

**Comment by stanleyxu2005** [comment]
But I am glad to see, if log4js natively supports some kind of right trimmed log message modifier.

**Comment by nomiddlename** [comment]
I think custom layout function is probably the only way to do this.
