### ISSUE TITLE
Is it possible to logging in JSON format using log4js?

### ISSUE THREAD

**Issue by pravin-logicap** [nomiddlename/log4js-node#362]
Hi,
log4js is working fine for me but I just want to log output into JSON format, so I can trace my output easily.

Is there any way to do?

Thanks.

**Comment by nomiddlename** [comment]
You can try to use the pattern layout to do what you want. Otherwise you may need to write your own layout function.

**Comment by pravin-logicap** [comment]
Thanks,
I created my own layout for printing log.

Regards,

Pravin Bhapkar
Logicap Software
http://logicapsoftware.webstarts.com/index.html <http://www.mindstix.com>
Email:pravinlogicap@gmail.com
Phone:+91-9860420380
          :+91-7276868231
Skype:pravin.bhapkar
