### ISSUE TITLE
Docs: 'npm install log4js'

### ISSUE THREAD

**Issue by leegee** [nomiddlename/log4js-node#363]
The docs say to `install log4js` but this project is `log4js-node` --- ?

**Comment by nomiddlename** [comment]
The npm package is `log4js`. The github repository is `log4js-node`. Is there an issue that needs fixing here?

**Comment by leegee** [comment]
Clarification in the documentation? This is the first time I've found a repository name that does not match the package name. Does this package differ from `log4js` hosted on GitHub? Hard to tell, since that's module's `README.md` simply says `Since March 2014 the new location of Log4js is at Github! The Framework was hosted on log4js.berlios.de for a long time`
