### ISSUE TITLE
Is it possible to also print the process id in the log?

### ISSUE THREAD

**Issue by xjmalm** [nomiddlename/log4js-node#370]
It should be useful if we use cluster.
For e.g., the format likes following:
[2016-04-06 13:44:00.252] **[process id xxx]** [DEBUG] default - some log text.

**Comment by nomiddlename** [comment]
You can use the pattern layout to do that (the token "%z" will be replaced by the process id).

**Comment by xjmalm** [comment]
Thanks @nomiddlename, it does work :)
