### ISSUE TITLE
Middleware Log Level doesn't seem to have any effect.

### ISSUE THREAD

**Issue by peek4y** [nomiddlename/log4js-node#372]
```app.use(log4js.connectLogger(logger, { level: log4js.levels.INFO }));```

The middleware's log level, seems to be just labeling and not filtering logs based on level.

If i set ```{ level: log4js.levels.ERROR }``` all the request logs are marked as error, irrespective of what the status code is.

**Comment by nomiddlename** [comment]
That's what it is supposed to do - you're specifying the log level that you want your http access to be logged as. You can specify a level of 'auto' if you want it to use different log levels based on http status codes (2xx - info, 3xx - warn, 4xx - error, 5xx - error). You can then use the normal log level filters on your appenders.

**Comment by nomiddlename** [comment]
Closing this because log4js is doing what it is supposed to do.
