### ISSUE TITLE
Logger reinitialization after restart

### ISSUE THREAD

**Issue by dedalus2011** [nomiddlename/log4js-node#376]
After shutting down the logger, we’ve experienced the issue that the logger cannot be properly reinitialized. The reason for shutting down the logger and then trying to restart is because we have developed an application that needs to unlock the log files and recreate them afterwards.

We were able to fix the issue by simply exporting the enableAllLogWrites function in the log4js.js class (**enableAllLogWrites:loggerModule.enableAllLogWrites**). 

module.exports = {
  getBufferedLogger: getBufferedLogger,
  getLogger: getLogger,
  getDefaultLogger: getDefaultLogger,
  hasLogger: hasLogger,

  addAppender: addAppender,
  loadAppender: loadAppender,
  clearAppenders: clearAppenders,
  configure: configure,
  shutdown: shutdown,

  ...

 **_ enableAllLogWrites:loggerModule.enableAllLogWrites_**
};

We would appreciate if you could integrate this fix in your current version.
Currently used version: **log4js@0.6.33**

**Comment by nomiddlename** [comment]
Shutdown/restart is supported in version 2.x onwards.
