### ISSUE TITLE
writing logFile as JSON

### ISSUE THREAD

**Issue by id0Sch** [nomiddlename/log4js-node#377]
hi,
we're trying to have the console ouput in the basic layout, but have the file written as jsons.
is that possible using the built-in appenders \ layouts?
thanks

**Comment by nomiddlename** [comment]
I think so - define two appenders in your config. One would be the normal console appender, the other a file appender with a custom layout function that just outputs the log event as JSON. To add the custom layout, call `log4js.layouts.addLayout(name, fnThatCreatesLayouts(config))` before calling `log4js.configure()`. I haven't tried this, but it should work.

I would be happy to accept a pull request to add a JSON layout function into the core, if this is something someone is willing to work on.

**Comment by id0Sch** [comment]
hi, thanks for the response.
i created a small node module that does exactly that
https://github.com/id0Sch/log4js-json-layout
i will add stuff to it and wait until it's mature enough and then i will submit a PR to your project and add it as a built-in layout - is that ok?

**Comment by nomiddlename** [comment]
That sounds great - thanks.
