### ISSUE TITLE
Not work properly in protractor

### ISSUE THREAD

**Issue by isian8814** [nomiddlename/log4js-node#379]
I am using log4js as logger, but since protractor is a a-synchronized.
The log4js is not working fine for appending to a file and out put info. 

Then I try the log4js-protractor-appender. The order of output is working fine as expected. However I still cannot append to a file.

Anyone has any suggestion?

**Comment by nomiddlename** [comment]
Closing this, as I assume the user has found a fix by now. Please re-open if you still need help.
