### ISSUE TITLE
Restart after shutdown

### ISSUE THREAD

**Issue by dominhhai** [nomiddlename/log4js-node#383]
How can I restart after calling `shutdown`?

**Comment by nomiddlename** [comment]
It's not really designed to do that, but I think you could just call `log4js.configure()` with your config file to set everything back up again.

**Comment by dominhhai** [comment]
`log4js.configure()` does not work after `shutdown`.
some thing like:
```javascript
function load () {
  log4js.configure('path/to/log4js.json')
}
.....
log4js.shutdown(function () {
 load()
})
```

and I got the error when writing logs: ` error happened  [Error: write after end]`

**Comment by nomiddlename** [comment]
Shutdown is really supposed to be used when your node process is about to die (like when you get an uncaught exception), it's not really written with re-starting in mind. Can you tell me a little bit about why you want to do this? Then maybe we can work something out.

**Comment by dominhhai** [comment]
I need to write some test case for ensuring the logs is worked ok.
I will delete these created logs before starting a new case.

**Comment by nomiddlename** [comment]
This is now possible in version 2.x
