### ISSUE TITLE
Is there a way to specify category names like a regex pattern?

### ISSUE THREAD

**Issue by techmoksha** [nomiddlename/log4js-node#392]
That would allow all category names conforming to the pattern to use same log config. Also would avoid duplication of configuration.

**Comment by acontreras89** [comment]
Any news on the subject?

**Comment by nomiddlename** [comment]
You can't use patterns for category names, but you can use hierarchies for sharing config. e.g. A category "cheese.gouda" would inherit the config for the category "cheese".
