### ISSUE TITLE
Buffered logger only stores first argument logged

### ISSUE THREAD

**Issue by djabraham** [nomiddlename/log4js-node#402]
Thanks for the buffered logger @eurekaa (pull https://github.com/nomiddlename/log4js-node/pull/231).  It's pretty awesome, and really cleans up tests. I just wish it buffered all the args as an array, rather than just the message itself, just for consistency. For example, when using the same appender and minimal layout, and logging more than one argument:

```
...error( { data: 'type of object as first arg' }, 'Message as second arg.' );
```

I would prefer to see this, which matches the base logger..

```
[ { data: 'type of object as first arg' }, 'Message as second arg.' ]
```

Rather than this, which is only the first arg passed to the buffered logger..

```
{ data: 'type of object as first arg' }
```

**EDIT**: One other minor thing, the base logger has a mark method that comes in handy at times. I just swapped it out with trace, for now :)

**Comment by djabraham** [comment]
A wrapper I am using, as temporary workaround..

    "use strict";
    var log4js = require('log4js');

    function getBufferedLogger(category) {
      var loggerBuffered = log4js.getBufferedLogger(category);

      function invokeWithArgsFunc (func) {
        return function invokeWithArgs() {
          var args = [];
          for (var a = 0; a < arguments.length; a++) {
            args[a - 0] = arguments[a];
          }
          return func(args);
        }
      }

      return {
        flush: loggerBuffered.flush,
        setLevel: loggerBuffered.trace,
        isLevelEnabled: loggerBuffered.isLevelEnabled,
        isTraceEnabled: loggerBuffered.isTraceEnabled,
        isDebugEnabled: loggerBuffered.isDebugEnabled,
        isInfoEnabled: loggerBuffered.isInfoEnabled,
        isWarnEnabled: loggerBuffered.isWarnEnabled,
        isErrorEnabled: loggerBuffered.isErrorEnabled,
        isFatalEnabled: loggerBuffered.isFatalEnabled,
        trace: invokeWithArgsFunc(loggerBuffered.trace),
        debug: invokeWithArgsFunc(loggerBuffered.debug),
        info: invokeWithArgsFunc(loggerBuffered.info),
        warn: invokeWithArgsFunc(loggerBuffered.warn),
        error: invokeWithArgsFunc(loggerBuffered.error),
        fatal: invokeWithArgsFunc(loggerBuffered.fatal)
      };
    }

    exports.getBufferedLogger = getBufferedLogger;

**Comment by nomiddlename** [comment]
The buffered logger can now be replaced by the recording appender from version 2.x onwards.
