### ISSUE TITLE
appender's level

### ISSUE THREAD

**Issue by alexey2baranov** [nomiddlename/log4js-node#404]
Hello! 

I want to know if it possible to set minimum log level for appender.

The use case of this is/ If i have some logger= new log4js("important.task") i would like to write all log messages into file and get errors on my email. 

```
logger.debug(some_message) //goes to file
logger.error(some_message) //goes to file and to email
```

**Comment by nomiddlename** [comment]
Take a look at the examples and tests for uses of the logLevelFilter which I think does what you want.
