### ISSUE TITLE
My log file is missing.

### ISSUE THREAD

**Issue by ykan** [nomiddlename/log4js-node#408]
Yesterday my server generate a log file about 3GB，but log file is missing after log rotate. I do not konw why?

Does any help?

nodejs: 4.2.1
pm2: 2.0.15
log4js:0.6.37

**Comment by nomiddlename** [comment]
How are you configuring log4js? Does log4js handle the log rotation, or is that controlled by the system?

**Comment by ykan** [comment]
I've found what cause this case. When I use pm2 cluster mode, one process start rotate log, then another process start rotate log again, but found log is already rotated, so it clean the log file. I guess~ Then I use `pmId`, so different process will have a log file.
