### ISSUE TITLE
Recreating the original log file when it's somehow renamed/deleted.

### ISSUE THREAD

**Issue by shunanya** [nomiddlename/log4js-node#409]
In continuation of issue #343 I would like to ask you the following:
My Node.js logs are rolled by Linux logrotate engine. So, the question is - how forcibly reopen original log files in real time (without stopping app) after original files are renamed by logrotate. 
I guess that log4js should be creating new original file and writing into. Now log4js is continue writing into renamed file. Do you have some example for that? Does such functionality exist in master branch?

Thank you in advance,

Simon

**Comment by nomiddlename** [comment]
This is going to need pull request #403 to fix the issue - I haven't had any time lately to look at it, but I'll see if I can sort something out over the weekend.

**Comment by nomiddlename** [comment]
The file appender now uses a SIGHUP listener, which logrotate can be configured to send to the process. Hope that fixes your issue. Released in version 1.0.0
