### ISSUE TITLE
Requiring module 557 which threw an exception

### ISSUE THREAD

**Issue by aayushanand99** [nomiddlename/log4js-node#410]
i am trying to include log4js in my react-native android project but it keeps throwing this error

**Comment by nomiddlename** [comment]
I'm going to need more to go on than this, sorry. I've never used react-native. Do you have some code to reproduce the issue?

**Comment by omhybrid** [comment]
yes i have a same error please give me solution

**Comment by nomiddlename** [comment]
Just demanding a solution won't work :) - give me some sample code that reproduces the error, and some information on your config.

**Comment by nomiddlename** [comment]
Closing this due to lack of information.
