### ISSUE TITLE
logger.log has a breaking change

### ISSUE THREAD

**Issue by fritx** [nomiddlename/log4js-node#411]
In `0.6.9-?`, `logger.log('some', 'string')` worked.
However, after upgraded to `?-0.6.38` at some time recently, `logger.log` logs empty content.

We did have been misusing the `.log` api along with `.debug` and `.info`, but... I guess it is actually a breaking change...

**Comment by WilixLead** [comment]
I have same issue in 1.1.1
```javascript
const log4js = require('log4js');
let abc = log4js.getLogger();
abc.log('First part', 'Second part');
```
And in result: 
`[2017-05-24 19:18:35.343] [INFO] [default] - Second part`

Node.js: v7.9.0
log4js: 1.1.1

**Comment by nomiddlename** [comment]
I've removed mention of `logger.log` from the docs for version 2.x to avoid future confusion. The first argument to `logger.log` was always supposed to be a log level, but I don't think this was made clear before. Sorry about the breaking change, but this should be the last time that happens.
