### ISSUE TITLE
Is it possible to write different level of log into different file?

### ISSUE THREAD

**Issue by FridaCai** [nomiddlename/log4js-node#412]
Is it possible to write different level of log into different file?

eg: 
message in log.info(**) will be written to info.log file
while message in log.error(**) will be written to error.log file 

it can be done in java log4j.

**Comment by nomiddlename** [comment]
Take a look at the logLevelFilter, which does what you want. There are examples in the examples directory, or take a look at the [example app](https://github.com/nomiddlename/log4js-example).
