### ISSUE TITLE
which appender to use to simply remote http loging

### ISSUE THREAD

**Issue by azulay7** [nomiddlename/log4js-node#415]
Hi,
Im confusing from the variety of options.
Which appender do I need to use, If I want to send log to remote http server.
**I'm using angular2 , and have bigger issue of loading the log4js module.

thank you in advance.
Amit.

**Comment by nomiddlename** [comment]
It would depend on the API your remote server uses. I think the loggly, logstash, logfaces, and slack appenders all use http as the transport, but there isn't anything like a generic http appender.

**Comment by azulay7** [comment]
Well I am not familiar with those appenders. I do know that I have a restfull api tuning on node.js soo I want my client side to send messages to this server.

**Comment by nomiddlename** [comment]
Closing this as there is no generic http appender.
