### ISSUE TITLE
when using angular2 , have issue of loading the log4js module.

### ISSUE THREAD

**Issue by azulay7** [nomiddlename/log4js-node#416]
![image](https://cloud.githubusercontent.com/assets/19120/19959594/9eb21a00-a1b0-11e6-8ab7-f1d0ac2bcedf.png)

**Comment by nomiddlename** [comment]
I've never used log4js in angular, sorry. It was written with server-side node applications in mind, so I'm not entirely sure it will work at all in the browser. Having said that, I know some people have used it successfully with browserify.

**Comment by nomiddlename** [comment]
Closing this, as no more information was given.
