### ISSUE TITLE
What are the breaking changes for log4js-node@1.0.0

### ISSUE THREAD

**Issue by blakambr** [nomiddlename/log4js-node#417]
With the update of the log4js module, are there any breaking changes between moving from 0.6.38 to 1.0.0 or was it just the dropping of support for node version < 0.12.x ?

Cheers

**Comment by nomiddlename** [comment]
I added a little section to the README about the changes. The main one is the change to the default appender from console to stdout, but there's also no more support for node 0.10 and a change to the way the compress option is passed to the file appenders.

**Comment by blakambr** [comment]
Alright awesome. That resolves my question. Thanks
