### ISSUE TITLE
Date format in Logfile as of Version 1.0.0

### ISSUE THREAD

**Issue by WearAHelmet** [nomiddlename/log4js-node#418]
Version 0.6.38 does not have this issue. Version 1.0.0 does, running on Linux:

<pre>
4.4.0-45-generic #66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
</pre>

running node v6.9.1

Log configured thus:
<pre>
log4js.configure({
  appenders: [
    { type: 'console' },
    { type: 'file', filename: log_file /*, category: 'my_project'*/ }
  ],
  replaceConsole: true
});
</pre>

Messages to console appear as expected. Date/time stamp in log is always:

<pre>
[NaN-NaN-NaN NaN:NaN:NaN.NaN]
</pre>

Example:

<pre>
[NaN-NaN-NaN NaN:NaN:NaN.NaN] [ERROR] app.js - @start
</pre>

**Comment by nomiddlename** [comment]
Thanks for catching this. I've published a fix in version 1.0.1

**Comment by WearAHelmet** [comment]
Thanks for a great package. I use log4js all the time.
