### ISSUE TITLE
pm2 cluster don't run 

### ISSUE THREAD

**Issue by songguangyu** [nomiddlename/log4js-node#422]
pm2 cluster don't run, who can help me!!

**Comment by nomiddlename** [comment]
You're going to have to give us more information than that if you want any help. Sample code, your log4js config, the error that gets produced. 

Just from reading the pm2 docs, I'd have to guess that you just need to configure log4js to use the stdout or stderr appenders, and then let pm2 handle all the log file management - I've never used pm2, so I'm only guessing.

**Comment by nomiddlename** [comment]
Closing this, as no more information was given.
