### ISSUE TITLE
High cpu usage with log4js

### ISSUE THREAD

**Issue by joveth** [nomiddlename/log4js-node#423]
I'm making an electron app on windows,using log4js@1.0.1 record information.But when logged it .The cpu runs 100% for a long time .(If you are making a demo ,just try several times) 
This is my config file log4js.conf:

    {
    "appenders": [
      { "type": "console" },
      { 
    	"type": "file",
     	"filename": "logs/log.log",
     	"maxLogSize": 2097152, 
     	"level": "DEBUG"
 	 }
     ]
    }

And my main.js is 

    var log4js = require('log4js');
    log4js.configure('log4js.conf', { reloadSecs: 300 });

As something is useful for me ,so the log4js module is important!

Needs helps!
Thanks.

**Comment by nomiddlename** [comment]
I couldn't reproduce this problem on my Mac with the code above. I'll try on my windows machine later, but is there anything else that could be causing this? The code in the example doesn't really do much - does it reproduce the issue every time on your machine?

**Comment by stanleyxu2005** [comment]
I'd like to know, what is the `reloadSecs` for?

**Comment by RichR** [comment]
@stanleyxu2005 reloadSecs is the duration in seconds that the configure function will check for an updated configuration file.

**Comment by joveth** [comment]
@nomiddlename Forgive my pool judgement . Maybe not the log module as I had removed all of them,but still happened few times . So maybe some other problems . I still could not solve it. But it's passed.

Thank you
