### ISSUE TITLE
Adding request id to connect logger

### ISSUE THREAD

**Issue by rustichowie** [nomiddlename/log4js-node#425]
Hi, Is it possible to add request parameters to logger when connecting it to express as below?
`app.use(log4js.connectLogger(httpLogger, { level: 'auto' }))`

**Comment by nomiddlename** [comment]
If you mean extracting url parameters as separate fields in the logs, i.e. `GET /thing?param=something` - and logging the `param` value in the output, then no. All url parameters will be logged in the url though (if it's a GET request, but POST bodies will not be logged).

**Comment by rustichowie** [comment]
No, i mean like a property on the `req` object. Ex: `req.id`.

**Comment by rkubik** [comment]
I have the same request. I'd love to be able to have an ID printed in each log entry that uniquely 
identifies each express request. I don't use `connectLogger` but here is an example:

    function setId(req, res, next) {
        req.id = uuidV4();
        next();
    }

    app.use(setId);
    app.use('/login', function(req, res, next) {
        logger.debug('<%s> New request', req.id);
    });

**Comment by rustichowie** [comment]
Hi rkubik. I figured out a way of doing this. See the code below:
```
app.use(log4js.connectLogger(httpLogger, { 
    level: 'auto', 
    format: (req, res, format) => {
      return format(`:remote-addr - ${req.c_id} - ":method :url HTTP/:http-version" :status :content-length ":referrer" ":user-agent"`);
    }
  }));
```
