### ISSUE TITLE
missing Logger.log function in @types/log4js

### ISSUE THREAD

**Issue by wudizhanche1000** [nomiddlename/log4js-node#431]
log function missing in the declaration file [https://github.com/DefinitelyTyped/DefinitelyTyped/tree/types-2.0/log4js](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/types-2.0/log4js)

**Comment by nomiddlename** [comment]
I don't have anything to do with this. Perhaps you should submit a pull request or create an issue on the DefinitelyTyped project instead?

**Comment by nomiddlename** [comment]
Closing this, because I don't think there's anything I can do.
