### ISSUE TITLE
How to set the default log level?

### ISSUE THREAD

**Issue by pallover** [nomiddlename/log4js-node#436]
I have some log4js config like this:
`var config = {
    appenders:[
        {
            type:"console"
        },
        {
            type: "file",
            filename: "file.log",
            maxLogSize: 20480,
            backups: 10
        }
    ],
    replaceConsole: true,
    levels: {}
}`
and used as : 
`var logger = log4js.getLogger();`

It works fine with logs output to console and file.log. The log content from `console.log()` is replaced with log4js style with log level 'INFO' as I learned. But when I call  `logger.setLevel('ERROR');` immedidately after calling `getLogger()`, the logs from `console.log()` are still present, both in the console and file.log. Shouldn't they disapprear after I restart the application?

**Comment by ericnewton76** [comment]
you added "replaceConsole:true" to the configuration... 

this replaces the default console.log function to send the message to log.info, which as defined by your configuration, is appended to "console" and to "file"

**Comment by pallover** [comment]
@ericnewton76  thanks for your kind reply. I‘ve updated the question to make it clear. I'm now still stucking    on that problem.

**Comment by nomiddlename** [comment]
Hi @pallover - sorry the extremely late reply. If you're still having problems with this, let me know - otherwise could you close this issue, please?

**Comment by nomiddlename** [comment]
Closing this one, as it seems to have been some confusion over how the loggers work. Please re-open if you still need help (I promise to respond sooner than 6 months later this time).
