### ISSUE TITLE
Hourly Rolling Pattern and Custom Layout Pattern in Appender is not working concurrently

### ISSUE THREAD

**Issue by haider0324** [nomiddlename/log4js-node#445]
**Hourly rolling logging file and in each file custom layout data appender is not working simultaneously**

I have created log.js class and in this class i had define custom appender. Firstly i set hourly rolling pattern and then set for layout pattern. but only layout pattern is working and not custom appender.

As you can see below mentioned quote snippet
```
log4js.configure({
	"appenders": [{
		/*"type": 'console',
		"category": "android_etm_log"}, {*/
		"category": "android_etm_log",
		"type": "logLevelFilter",
		"level": "WARN",
		"appender": {
			"type": "file",
			"filename": "logs/error.log",
			"pattern":"-dd--hh.log",
			"layout": {
				"type": "pattern",
				"pattern": '[%d] [%p] - %m' //%n for new line return
			}
		}
	},{
		"category": "android_etm_log",
		"type": "file",
		"filename": "logs/info.log",
		"pattern":"-dd--hh.log",
		"layout": {
			"type": "pattern",
			"pattern": '[%d] [%p] - %m'
				//"pattern": '[%d] [%p] - %m'
		}
	}],

	"levels": {
		"android_etm_log": "TRACE"
	}
});
```

and my log data with custom layout appender is mentioned below which i get in log file
```
[2017-02-21 16:43:04.263] [ERROR] - {"TICKETDETAILS":[{"MESSAGEID":"etmandroid ","TICKET_CANCEL_STATUS":"0","TRXNID":"00001","USERTYPE":"1","TRIPID":"12345","ETMUID":"654321","ORIGINSTAGE_ID":"123","DESTSTAGE_ID":"234","AMOUNT":"10","USERCOUNT":"2","TIMESTAMPING":"101010"}]}
```

As per github post and issues i have passed hourly rolling pattern and layout pattern in appender but still unable to get the desired out. And also not getting hourly rolling file in my storage. Please suggest me how i can do this.

**Comment by nomiddlename** [comment]
Use "dateFile" as the appender type instead of "file" - I think that will solve your problem.

**Comment by nomiddlename** [comment]
I'm assuming that swapping to `dateFile` fixed your problem, so I'm going to close this issue.

**Comment by haider0324** [comment]
Hi nomiddlename,

 yaah it's working now and sorry to forget to say thanks
