### ISSUE TITLE
How can I shut off the timestamp from printing to the console?

### ISSUE THREAD

**Issue by tremaineeto** [nomiddlename/log4js-node#446]
For my use case, I need to shut off the timestamp (e.g. [2017-02-22 21:32:53.012]) from printing to the console when I use the log4js logger. Is there a configuration I would need to set for this?

**Comment by addykim** [comment]
I'm in a similar boat as you. You may want to check out [the layout page](https://github.com/nomiddlename/log4js-node/wiki/Layouts) in the wiki.

**Comment by addykim** [comment]
At the time of my last post I had a syntax error that prevented me from getting it to work. Here's how I've been successfully able to achieve something similar to what you want:

```
const log4js          = require('log4js');


const log_format = {
                'type': 'pattern',
                'pattern': "[%p] - %m %n"
            };

log4js.configure({
    appenders: [{
        type: 'file', filename: '/code/file.log', layout: log_format
    },
    {type: 'console', layout: log_format}]
});
```

Note that you have to add this layout to every single appender, so I created the `log_format` object and passed it to layout.

**Comment by qimenxiaozi** [comment]
just an example for you as below:

function newLoggerWithCategory(filename, category) {
  log4js.loadAppender('dateFile');

  // appender(filename, pattern, alwaysIncludePattern, layout, timezoneOffset)
  log4js.addAppender(log4js.appenders.dateFile(filename, ".yyyyMMdd", false, log4js.layouts.messagePassThroughLayout), category);
  log4js.addAppender(log4js.appenders.dateFile(filename, ".yyyyMMdd",      log4js.layouts.messagePassThroughLayout), category);
  
  let log = log4js.getLogger(category);
  log.setLevel('INFO');
  return log;
}

**Comment by nomiddlename** [comment]
Assuming these examples solved the problem for the user, closing.
