### ISSUE TITLE
Not flushing to file

### ISSUE THREAD

**Issue by robertcrowe** [nomiddlename/log4js-node#448]
I'm having trouble getting log4js-node to write to a file.  It creates the file, but none of the log messages are written to the file.  Here's an example:
```
var log4js = require('log4js'); 
//console log is loaded by default, so you won't normally need to do this
//log4js.loadAppender('console');
log4js.loadAppender('file');
//log4js.addAppender(log4js.appenders.console());
log4js.addAppender(log4js.appenders.file('cheese.log'), 'cheese');

var logger = log4js.getLogger('cheese');
logger.setLevel('ALL');

logger.trace('Entering cheese testing');
logger.debug('Got cheese.');
logger.info('Cheese is Gouda.');
logger.warn('Cheese is quite smelly.');
logger.error('Cheese is too ripe!');
logger.fatal('Cheese was breeding ground for listeria.');

process.exit(0);
```

I've also tried ending it with:

`log4js.shutdown(process.exit(0));
`

but that didn't work either.  I've searched the wiki.  If I don't exit the process and wait a few seconds the messages are written to the file, but I don't want to leave the process running indefinitely.  How do I get this to work?

**Comment by nomiddlename** [comment]
Because the file writes are asynchronous, your program is exiting before the output has been written. You were nearly there with the shutdown call - but shutdown takes a function to execute, so you'd need something like this:
```javascript
log4js.shutdown(function() { process.exit(0); });
```
Give that a try.

**Comment by nomiddlename** [comment]
I'm going to assume that fixed your issue and close this.

**Comment by robertcrowe** [comment]
Sorry, yes, I did.  It was what you said it was, a race condition between the flush and the process.exit().  The call to log4js.shutdown(() => { process.exit(0) } ) worked, or just waiting a few seconds also worked.
