### ISSUE TITLE
can you add redis appender?

### ISSUE THREAD

**Issue by wadecha** [nomiddlename/log4js-node#451]
I want use redis publish log, so I hope you can add redis appender, code: 

"use strict";
var layouts = require('../layouts');
var redis = require('redis');
var util = require('util');
function redisAppender(host, port, pass, channel, layout) {
	layout = layout || layouts.messagePassThroughLayout;
	var redisClient = redis.createClient(port, host, {auth_pass: pass});
	redisClient.on('error', function (err) {
		if (err) {
			console.error(
					"log4js.redisAppender - %s:%p Error: %s", host, port, util.inspect(err)
			);
		}
	});
	return function (loggingEvent) {
		var message = layout(loggingEvent);
		redisClient.publish(channel, message, function (err) {
			if (err) {
				console.error(
						"log4js.redisAppender - %s:%p Error: %s", host, port, util.inspect(err)
				);
			}
		});
	};
}

function configure(config) {
	var layout, host, port, pass, channel;
	if (config.layout) {
		layout = layouts.layout(config.layout.type, config.layout);
	}
	host = config.host ? config.host : '127.0.0.1';
	port = config.port ? config.port : 6379;
	pass = config.pass ? config.pass : '';
	channel = config.channel ? config.channel : 'log';
	return redisAppender(host, port, pass, channel, layout);
}

exports.appender = redisAppender;
exports.configure = configure;

**Comment by nomiddlename** [comment]
Thanks for this. I'd be happy to accept a Redis appender. The right way to submit code is to create a pull request - take a look at the [contribution instructions](https://github.com/nomiddlename/log4js-node/wiki/Contributing) and Github's docs on [pull requests](https://help.github.com/articles/about-pull-requests/).

**Comment by wadecha** [comment]
I don't know why check failed, the error note is 'error Parsing error: Unexpected token'. I use ES5.1, so I don't know how correct the code. [#452](https://github.com/nomiddlename/log4js-node/pull/452)

**Comment by nomiddlename** [comment]
Fixed by #452
