### ISSUE TITLE
console logger not multiprocess-safe

### ISSUE THREAD

**Issue by jpstotz** [nomiddlename/log4js-node#456]
Using the following logger configuration the output on the console on Windows is not correct when using multiple processes.

```
{
	type: 'console',
	layout: {
		type: 'pattern',
		pattern: '%z [%r] [%[%5.5p%]] - %m'
	}
}
```

Even removing the colored-block only reduces the probability to get a "merged" log output like this:

Sample output:

> 11964 [11:34:32] [ INFO] - Listening on port 3000...
> 6136 [11:34:32] [ INFO] - Listening on port 3000...
> 9736 [11:34:32] [10120 [11:34:32] [ INFO INFO] - Listening on port 3000...
> ] - Listening on port 3000...
> 10076 [11:34:32] [ INFO8564 [11:34:32] [] - Listening on port 3000...
>  INFO] - Listening on port 3000...
> 10084 [11:34:32] [ INFO] - Listening on port 3000...
> 14048 [11:34:32] [ INFO] - Listening on port 3000...

**Comment by nomiddlename** [comment]
Yep, that's why there's a [multi-process appender](https://github.com/nomiddlename/log4js-node/wiki/Multiprocess) - that might be what you need.
