### ISSUE TITLE
pattern %z (process id) can not be padded/truncated

### ISSUE THREAD

**Issue by jpstotz** [nomiddlename/log4js-node#457]
When specifying a pattern like `%10z` to insert the process id into the log file the padding to 10 characters is ignored.

I assume that the `pid` is handled internally as number and not as string, hence padding and truncation do not work. 

For example if the pattern `%10.10z` is used the following exception is thrown:

> TypeError: toTruncate.substring is not a function
>     at truncate (node_modules\log4js\lib\layouts.js:290:25)
>     at truncateAndPad (node_modules\log4js\lib\layouts.js:318:19)
>     at node_modules\log4js\lib\layouts.js:343:28
>     at Logger.<anonymous> (node_modules\log4js\lib\appenders\console.js:8:16)

My current workaround is to define my own pid as string:

```
pattern: '%6x{pid} [%r] [%[%5.5p%]] - %m',
tokens: {
	'pid': function () {
		return process.pid.toString();
	}
}
```

**Comment by nomiddlename** [comment]
Release in version 2.0.0 (if not before)
