### ISSUE TITLE
How to read recent logs?

### ISSUE THREAD

**Issue by niranjans** [nomiddlename/log4js-node#458]
I was going through the documentation but I could not figure out how to read the logs through code or if it is even possible. 

I would like to display the recent (last 100 lines?) logs collected by the logger in one part of the app but not sure which method to use.

**Comment by nomiddlename** [comment]
There's no direct way to do this right now. You could write your own appender that stores the last 100 log messages, and forwards on to another appender. Take a look at the way `logLevelFilter` works for an idea of how to implement.

**Comment by nomiddlename** [comment]
Closing this, not really a feature of log4js.
