### ISSUE TITLE
Problem reading log4js config  on browser -- using browserify

### ISSUE THREAD

**Issue by Synaccord** [nomiddlename/log4js-node#466]
I am using v1.1.1 from npm.  (the 3/27/2017 version 2e3cb97 on GitHub generates a build error when I try to use it - will report separately)

It works great on the server side node code.

But, for code that runs on the browser side, when I use either
`var log4js = require('log4js');`
 or
`import log4js from 'log4js';
`
I get this error: 

Uncaught Error: Problem reading log4js config { appenders: [ { type: 'stdout' } ], replaceConsole: false }. Error was "Cannot find module 'stdout'" (Error: Cannot find module 'stdout'

this is before trying to execute log4js.configuration or anything else.   It blows up on the import/require

I'm using browserify and have an integrated environment generating server side and browser side code and I'm trying to make this work.

**Comment by nomiddlename** [comment]
I know people have managed to get browserify to work in the past (with previous versions of log4js). The error you're seeing comes from the default config setup. When you require log4js the last thing it does is call `configure` itself with the default config (which is what you're seeing in the error message). The `stdout` appender uses `process.stdout` - does browserify make this available? Older versions of log4js defaulted to the console appender, but node's console.log output had a high memory usage problem.

**Comment by nomiddlename** [comment]
Perhaps this library can help? https://github.com/kumavis/browser-stdout

**Comment by Synaccord** [comment]
The error message _Error: Cannot find module 'stdout'_was actually from require() failing.  The appenders are not available because browserify has optimized them out because they are not being 'used'.

I did two things to fix this. First, instead of just require('log4js'), I had to do this:
`if(typeof window !== 'undefined') {
  process.env.LOG4JS_CONFIG= {appenders: [{ type: 'bconsole' }]};
  var log4js = require('log4js');
  window.logger = log4js.getLogger('browser');
  window.logger.setLevel("INFO");
  logger.info("client main running on browser");
}`

Browserify does create a process variable (but there is no stdout in it).  By setting the env before loading log4js I was able to get it to load the appender that wasn't going to create an error.

And then in browserify  I had to explicitly require the module from it's build path and I named it bconsole so it wouldn't conflict with console.

`browserify dist/client/main.js --require ./node_modules/log4js/lib/appenders/console.js:bconsole -o assets/js/main.js`

That was enough to get it working - but the output isn't as good as just using console.log which will give you expandable objects, rather than just printing them all out.  So then I created a new bconsole.js:

bconsole.js
`"use strict";

// on the broswer, console.log displays objects in a way that is compact and lets you expand them through the UI.
// so this default layout will preserve the objects and pass them to console.log
function bconsoleAppender (layout, timezoneOffset) {
  layout = layout || function(e,t){
    var d=e.startTime.toString().split(' '); 
    return [d[3]+d[1]+d[2]+' '+d[4],
     e.categoryName, ...e.data]
  }
  return function(loggingEvent) {
    console.log(...layout(loggingEvent, timezoneOffset));
  };
}

function configure(config) {
  var layout;
  if (config.layout) {
    layout = layouts.layout(config.layout.type, config.layout);
  }
  return bconsoleAppender(layout, config.timezoneOffset);
}

exports.appender = bconsoleAppender;
exports.configure = configure;`

And then I pulled that in through browserify:
`browserify dist/client/main.js --require ./dist/client/bconsole.js:bconsole -o assets/js/main.js`

I'm excited to be using this in my code that runs both on node and on the browser and I hope this will help the next person.

**Comment by Synaccord** [comment]
So I have resolved this issue and you can close the issue, and if you agree with this let me know. I could add this to the documentation or you can, and I'm happy to contribute the new appender.

**Comment by nomiddlename** [comment]
Thanks for this - it would be awesome if you can add this to the wiki - especially the trick of defining LOG4JS_CONFIG. 

My only concern with the appender is that it uses the `...` operator, which doesn't work on node v4 (which I still support). I also wonder whether it might be worth replacing the console appender with this browser-compatible version, since the console appender is really only useful in the browser (it's better to use the stdout appender server-side).
