### ISSUE TITLE
uglify fails with this error

### ISSUE THREAD

**Issue by Synaccord** [nomiddlename/log4js-node#467]
Related to #466 

When I use the 3/27/2017 version 2e3cb97 from git, and I 
`import log4js from "log4js";`
And then I browserify and then I get this error when I uglify
Parse error at assets/js/main.js:57337,6
SyntaxError: Unexpected token: name (Configuration)

Will post more details as I dig in.

**Comment by nomiddlename** [comment]
Closing this, assuming the user managed to fix the problem.
