### ISSUE TITLE
Force single line output by Console appender?

### ISSUE THREAD

**Issue by saml** [nomiddlename/log4js-node#471]
This is a question, not an issue. 

I'm passing multiple arguments to `logger.info('message', obj1, obj2)`  and those objects are pretty printed (via `util.format`, I think):
```js
$ node
> var log4js = require('log4js')
> var log = log4js.getLogger()
> log.info('message', log4js)
[2017-04-10 16:49:59.829] [INFO] [default] - message { getBufferedLogger: [Function: getBufferedLogger],
  getLogger: [Function: getLogger],
  getDefaultLogger: [Function: getDefaultLogger],
  hasLogger: [Function: hasLogger],
  addAppender: [Function: addAppender],
  loadAppender: [Function: loadAppender],
  clearAppenders: [Function: clearAppenders],
....
```

Ideally,
```js
> log.info('message', log4js)
[2017-04-10 16:49:59.829] [INFO] [default] - message { getBufferedLogger: [Function: getBufferedLogger],\n  getLogger: [Function: getLogger],\n  getDefaultLogger: [Function: getDefaultLogger],\n  hasLogger: [Function: hasLogger],\n...
```

Is there a way to force Console appender to always output a single line? New line character is special for many log processors, and I want each log entry to have new line characters properly escaped.

I don't (and can't) necessarily need proper JSON encoding of objects because some objects that I'm logging aren't JSON serializable. 

I should serialize to string myself and only call `logger.info(oneStringMessage)` with one argument.. but I have a big set of applications that all pass multiple arguments to log methods.

**Comment by nomiddlename** [comment]
You might be able to do this using a [patternLayout](https://github.com/nomiddlename/log4js-node/wiki/Layouts) with a custom replacement token. Something like this:

```javascript
var config = {
    appenders: [{
        type: "console",
        layout: {
            type    : "pattern",
            pattern : "%d{ABSOLUTE} %[%-5p%] %c %x{singleLine}",
            tokens: {
                singleLine : function(logEvent) {
                  // logEvent.data is an array that contains the arguments to the log.info() call
                  return logEvent.data[0] + ', ' + logEvent.data[1].toString();
                }
            }
        }
    }]
};
log4js.configure(config);
```

Obviously, you'd need to do something a bit more sophisticated in the `singleLine` function above.

**Comment by saml** [comment]
Thank you!

```js
> log4js.configure({appenders:[{type:'console',layout:{type:'pattern',pattern:'%x{msg} %x{json}',tokens:{msg(ev) {return ev.data[0]}, json(ev) {return jsonStringify(ev.data.splice(1))}}}}]})
> var a = {foo:'bar'}
> a.a = a
> logger.info('foo', a, log4js)
foo [{"foo":"bar","a":"[Circular]"},{"levels":{"ALL":{"level": ....]

> log4js.configure({appenders:[{type:'console',layout:{type:'pattern',pattern:'%x{inspect}',tokens:{inspect(ev) {return util.format.apply(util, ev.data).replace(/\n/g, '\\n')}}}}]})
> logger.info('foo', a, log4js)
foo { foo: 'bar', a: [Circular] } { getBufferedLogger: [Function: getBufferedLogger],\n  getLogger: ... }
```

**Comment by ricardosaracino** [comment]
> ```js
>  singleLine : function(logEvent) {
>                   // logEvent.data is an array that contains the arguments to the log.info() call
>                   return logEvent.data[0] + ', ' + logEvent.data[1].toString();
>                 }
>             }
>         }
> ```

This worked perfectly for me to do a csv escape .. 😎
