### ISSUE TITLE
Document about logstashUDP is missing.

### ISSUE THREAD

**Issue by Rukeith** [nomiddlename/log4js-node#475]
I went to the official website. But I couldn't find the page about logstashUDP.  
I still couldn't find the information about logstashUDP at github wiki.

![2017-04-24 09 21 56](https://cloud.githubusercontent.com/assets/7069605/25319357/9de74284-28cf-11e7-85e9-b3a0370ca436.png)

![2017-04-24 09 20 59](https://cloud.githubusercontent.com/assets/7069605/25319345/61436574-28cf-11e7-9308-715b3be3de3d.png)

**Comment by nomiddlename** [comment]
Yep. The docs aren't written yet for version 2.x. 

If you're using v1.1.x and below, then there's [some example code](https://github.com/nomiddlename/log4js-node/blob/master/examples/logstashUDP.js)

**Comment by Rukeith** [comment]
Thanks a lot!  
I really need this.
