### ISSUE TITLE
Docs broken?

### ISSUE THREAD

**Issue by kingchad** [nomiddlename/log4js-node#481]
Lay outs section of your documents appears to not exist. I'm not familiar enough with your project to know if it ever existed. Feel free to close if this is erroneous.

**Comment by joshliptzin** [comment]
Yes docs appear to be completely broken. Even copying the minimalist version on the front page is broken.

**Comment by nomiddlename** [comment]
In the first few lines of the Readme I mention that these docs are for the version 2.x release, which is not yet available. There's a link there for the version 1.1.x docs which are for the current version in npm. Version 2 will be released as soon as I've finished writing the docs.

**Comment by kingchad** [comment]
apologies, i missed that in the readme.
