### ISSUE TITLE
datefile now is  undefined

### ISSUE THREAD

**Issue by achillesye** [nomiddlename/log4js-node#482]
logconfig {
      "type": "dateFile",
      "filename": "/storage/logs/mysql",
      "maxLogSize": 20480,
      "backups": 3,
      "pattern": "_yyyy-MM-dd.log",
      "alwaysIncludePattern": true,
      "category": "mysql"
    },

streamroller:DateRollingFileStream Now is  +0ms undefined
streamroller:DateRollingFileStream this.now is  +2ms function now() { [native code] } , now is  undefined

How to deal with this problem？？

**Comment by nomiddlename** [comment]
That's not a problem. Those two debug lines just indicate that a custom `now` function (used in testing) was not passed in, and that streamroller is defaulting to `Date.now()` instead.
