### ISSUE TITLE
configure covered

### ISSUE THREAD

**Issue by x403368945** [nomiddlename/log4js-node#483]
app.js
(function() {
    const app = require('./10001');
    app.set('port', 10001);
    const server = app.listen(app.get('port'), function() {
          console.log('Express server listening on port ', server.address().port, " with pid ", process.pid);
    });
})();
(function() {
    const app = require('./10002');
    app.set('port', 10002);
    const server = app.listen(app.get('port'), function() {
        console.log('Express server listening on port ', server.address().port, " with pid ", process.pid);
    });
})();

port (10001&10002) in the same process, port 10002 use log4js.configure() replace port 10001 use log4js.configure()

**Comment by nomiddlename** [comment]
What is the bug here? I don't understand.

**Comment by nomiddlename** [comment]
Closing this due to lack of information. Feel free to re-open if you can give me more info. Thanks.
