### ISSUE TITLE
the configure found an error

### ISSUE THREAD

**Issue by miss61008596** [nomiddlename/log4js-node#485]
this is my test code :

![image](https://cloud.githubusercontent.com/assets/6361237/26823082/deb2594e-4ade-11e7-8674-d25a8e1d94c8.png)

and the lib code :

![image](https://cloud.githubusercontent.com/assets/6361237/26823523/83331340-4ae0-11e7-867b-0644314fe0b6.png)

I try to use the following code ,it works,

![image](https://cloud.githubusercontent.com/assets/6361237/26823454/48e9c490-4ae0-11e7-891c-c6aee85abe12.png)

I need your help ,thanks

**Comment by nomiddlename** [comment]
Hi, this looks like you're mixing log4js v2.x configuration with v1.1.x code. This is my fault - the documentation on github is all for v2, but that version has not yet been released to npm. The version in npm is 1.1.x - the documentation for that is [here](https://github.com/nomiddlename/log4js-node/tree/v1.1.1)

**Comment by miss61008596** [comment]
Thank you, and we Look forward to use v2.x, and log4js is fantastic。
