### ISSUE TITLE
how to append api execution time in log file

### ISSUE THREAD

**Issue by huyntsgs** [nomiddlename/log4js-node#487]
When execution node js in console, there is the summary execution time of REST api as following.
How can i append this to log4j log file? Thanks!

POST /baserouter/openapp 404 42.079 ms - 258

**Comment by nomiddlename** [comment]
If this is being sent to the console, and you're using version 1.1.1 or earlier of log4js, then you can try adding `replaceConsole: true` to your log4js config. 

Note that this will not work in log4js version 2.x (but that's not released yet anyway, so don't worry too much)
