### ISSUE TITLE
Console appender performance improvement

### ISSUE THREAD

**Issue by jorgemsrs** [nomiddlename/log4js-node#490]
The console appender currently delegates all write operations to `console.log`. The current implementation uses `util.format` which introduces a slight performance penalty (https://github.com/nodejs/node/blob/master/lib/console.js#L82). 

I propose change the delegation to `process.stdout` which is a `WritableStream` and, thereof, is the lower level and leaner substitute.

For nodejs 8.1.1 the figures are:
benchConsoleLog*100000: 7270.032ms
benchProcessWriteIgnoreErrors*100000: 3207.920ms
benchProcessWriteCatchErrors*100000: 5114.261ms

For nodejs 6.11.0:
benchConsoleLog*100000: 4435.085ms
benchProcessWriteIgnoreErrors*100000: 3712.785ms
benchProcessWriteCatchErrors*100000: 6784.424ms

I've created a gist do showcase this behaviour. Please refer to `benchProcessWriteIgnoreErrors` for the desired and equivalent substitute:
https://gist.github.com/jorgemsrs/4a5aa24cc89f13027ea27f2d1b9c517f

**Comment by nomiddlename** [comment]
Closing this - stdout appender already exists.
