### ISSUE TITLE
addContext is not released yet - and we rely on that

### ISSUE THREAD

**Issue by oskarszura** [nomiddlename/log4js-node#495]
Hi,

Just wanted to ping, when `addContext` will be released (it's not within `v1.1.1` as we (the company I'm working currently in) need to apply additional tokens in runtime. 

When `addContext` can be released?

https://github.com/nomiddlename/log4js-node/blame/117531901c21a3ae74a74fb466b355708eef3fcf/lib/logger.js#L84

**Comment by oskarszura** [comment]
FYI: @nomiddlename - this feature is essential for us, so if you'll find time for a response, I'd appreciate much. Thank you in advance and kudos for this repo!

**Comment by nomiddlename** [comment]
I should be able to release 2.x in the next week or two - I've just got to finish up the log4js-api work mentioned in issue #493, and the memory problem in #494
