### ISSUE TITLE
must have a property "appenders" of type object.

### ISSUE THREAD

**Issue by kalsolio** [nomiddlename/log4js-node#500]
`
log4js.configure({
    appenders: [
        { type: 'console' },
        { type: 'dateFile', filename: 'logs/task',"pattern":"-dd.log", alwaysIncludePattern:true,category: 'task' },
        { type: 'dateFile', filename: 'logs/result',"pattern":"-dd.log", alwaysIncludePattern:true,category: 'result' },
        { type: 'dateFile', filename: 'logs/error', "pattern":"-dd.log",alwaysIncludePattern:true,category: 'error' },
        { type: 'dateFile', filename: 'logs/default', "pattern":"-dd.log",alwaysIncludePattern:true,category: 'default' },
        { type: 'dateFile', filename: 'logs/rate', "pattern":"-dd.log",alwaysIncludePattern:true,category: 'rate' }
    ]
});
`

then. 
       ` throw new Error(
        ^

Error: Problem with log4js configuration: ({ appenders: 
   [ { type: 'console' },
     { type: 'dateFile',
       filename: 'logs/task',
       pattern: '-dd.log',
       alwaysIncludePattern: true,
       category: 'task' },
     { type: 'dateFile',
       filename: 'logs/result',
       pattern: '-dd.log',
       alwaysIncludePattern: true,
       category: 'result' },
     { type: 'dateFile',
       filename: 'logs/error',
       pattern: '-dd.log',
       alwaysIncludePattern: true,
       category: 'error' },
     { type: 'dateFile',
       filename: 'logs/default',
       pattern: '-dd.log',
       alwaysIncludePattern: true,
       category: 'default' },
     { type: 'dateFile',
       filename: 'logs/rate',
       pattern: '-dd.log',
       alwaysIncludePattern: true,
       category: 'rate' } ] }) - must have a property "appenders" of type object.`

**Comment by nomiddlename** [comment]
Configuration format changed in version 2.x (take a look at the [docs](https://nomiddlename.github.io/log4js-node/appenders.html))

**Comment by nomiddlename** [comment]
The 2.x equivalent of the above would be something like:
```javascript
log4js.configure({ 
  appenders: {
    out: { type: 'console' }, 
    task: { type: 'dateFile', filename: 'logs/task',"pattern":"-dd.log", alwaysIncludePattern:true }, 
    result: { type: 'dateFile', filename: 'logs/result',"pattern":"-dd.log", alwaysIncludePattern:true}, 
    error: { type: 'dateFile', filename: 'logs/error', "pattern":"-dd.log",alwaysIncludePattern:true}, 
    default: { type: 'dateFile', filename: 'logs/default', "pattern":"-dd.log",alwaysIncludePattern:true}, 
    rate: { type: 'dateFile', filename: 'logs/rate', "pattern":"-dd.log",alwaysIncludePattern:true} 
  },
  categories: {
    default: { appenders: ['out','default'], level: 'info' },
    task: { appenders: ['task'], level: 'info'},
    result: { appenders: ['result'], level: 'info' },
    error: { appenders: ['error'], level: 'error' },
    rate: { appenders: ['rate'], level: 'info' }
  }
);
```

**Comment by matz1237** [comment]
**I have this :-** 
log4js.configure({
	appenders: [
		{ type: 'console' },
		{ type: 'file', filename: 'logs/site.log' }
	]
});
var logger = log4js.getLogger();


**So i changed to this :-**

log4js.configure({
	appenders: {
		out:{ type: 'console' },
		app:{ type: 'file', filename: 'logs/site.log' }
	},
	categories: {
    default: { appenders: [ 'out', 'app' ], level: 'debug' }
  }
});
var logger = log4js.getLogger();



Is this right ?

**Comment by nomiddlename** [comment]
That looks correct to me, yes.

**Comment by matz1237** [comment]
thankyou 👍

**Comment by CherryCHan** [comment]
I want to use 'replaceConsole'. How to use it in the newest version?

**Comment by nomiddlename** [comment]
I removed `replaceConsole` - it caused a few weird errors, and I wasn't entirely comfortable with messing around with a core part of node. If you still want to do this, then code like this should do the trick:
```javascript
log4js.configure(...); // set up your categories and appenders
const logger = log4js.getLogger('console');
console.log = logger.info.bind(logger); // do the same for others - console.debug, etc.
```

**Comment by nomiddlename** [comment]
Closing this - I think all problems have been addressed. Please open a new issue if you find something else wrong.
