### ISSUE TITLE
Logging methods throw errors when a value doesn't support toString

### ISSUE THREAD

**Issue by morungos** [nomiddlename/log4js-node#501]
There's a weird corner case where if a logging argument doesn't have a `toString()` method, and consequently doesn't interpolate into strings, the logging function itself throws an error on its internal `debug()` call. 

I've just spent a few hours on this, and it seems to be triggered by `superagent` and/or `express` making a request body that doesn't have a `toString()` method. I'd just passed it to a log function, and all worked well before I updated to 2.0.

The specific line at issue is: https://github.com/nomiddlename/log4js-node/blob/master/lib/logger.js#L87

I admit that this had never occurred to me, but normal console logging doesn't appear vulnerable to this issue, and I don't really think a normal logging user should have to guard against `logger.debug()` throwing an error, which is what was happening here. 

I've worked around it for now by forcing the data into a normal object, but what the best solution is, whether some prototype detection or `try` / `catch`, I'm not sure. Alternatively, since this is for debug purposes only, you could maybe even not pass log value data through  to `debug()`.

**Comment by nomiddlename** [comment]
Do you have some example code that triggers this? I'm struggling to come up with an object definition that doesn't have a `toString()` function, since that's present for all objects. I'd like to make sure this is the only place that has this problem, and that would be easier if I could reproduce it.

**Comment by morungos** [comment]
Nothing that isn't a massive tangle of dependencies, but I'd guess that:

    Object.create(null)

Creates a value that doesn't descend from `Object`. Just adding that to a logger method call as a value should demonstrate the issue.

**Comment by nomiddlename** [comment]
Published a fix for this to NPM in version 2.1.0

**Comment by morungos** [comment]
Excellent. Many thanks.
