### ISSUE TITLE
(logLevelFilter) appender is not a function

### ISSUE THREAD

**Issue by victor0801x** [nomiddlename/log4js-node#502]
according doc logLevelFilter example,  { type: 'logLevelFilter', appender: ['emergencies'], level: 'error' }
will get appender is not a function error

but Configuration say appender property is string type { type: 'logLevelFilter', appender: 'emergencies', level: 'error' }, that will work

is appender property will accept array ?

**Comment by nomiddlename** [comment]
Thanks for that - it was a mistake in the example code for the logLevelFilter. The appender property of the filter is a string, not an array.
