### ISSUE TITLE
Migrating guide from 1.x

### ISSUE THREAD

**Issue by Cap32** [nomiddlename/log4js-node#508]
Is there any guide for migrating from 1.x? Or is there any breaking change in 2.x?

Thanks

**Comment by nomiddlename** [comment]
Sorry - there's no migration guide - I'll write one soon. There's only this [document](https://github.com/nomiddlename/log4js-node/blob/master/v2-changes.md) that gathers some of the changes, but that was more like notes for me to remember than something that would be useful for you. Main changes for users are in the way log4js is configured.

**Comment by nomiddlename** [comment]
I've added some docs about migrating: https://nomiddlename.github.io/log4js-node/migration-guide.html - hope that helps.
