### ISSUE TITLE
while run the app by pm2, the log4js do not work!

### ISSUE THREAD

**Issue by Sailor20** [nomiddlename/log4js-node#511]
while run the app by pm2, the log4js do not work! what should i do?

thanks for first

**Comment by nomiddlename** [comment]
Like I said in your previous issue #510 - this is a duplicate of #265, so I'm going to close this. PM2 will not work with version 2.x until pull request #509 is merged. This will be very soon (we are talking within a couple of days only), so please wait until then. 

Please read issue #265 for more information.

**Comment by Sailor20** [comment]
sorry, I can not see the pre previous was answered, thanks
