### ISSUE TITLE
Depends on deprecated version of nodemailer.

### ISSUE THREAD

**Issue by southeastcon2017** [nomiddlename/log4js-node#513]
Should upgrade dependency to use the final version of nodemailer, version 4.0.1

**Comment by nomiddlename** [comment]
Version 4.0.1 requires a node version >= 6, but log4js supports node versions >= 4. It's only an optional dependency anyway, so you're free to install nodemailer@4.0.1 if you want - as far as I know it should work, the API looks the same to me. If you know that the smtp appender definitely doesn't work with nodemailer v4, then please re-open this issue with some details about the problem.
