### ISSUE TITLE
Still about pm2 

### ISSUE THREAD

**Issue by yuzhigang33** [nomiddlename/log4js-node#514]
1.  does log4js@1.1.1 support pm2 cluster mode?
2.  I got errors with pm2-intercom, i do not use node-config
```
pm2 version : 2.6.1
node version: 8.2.1

errors:   ID, DATA or TOPIC field is missing
```

```
{
    level:'DEBUG',
    appenders: {
     ....
    }
    categories: {
      ...
    }
    pm2: true
 }
```

**Comment by nomiddlename** [comment]
You need log4js 2.3.0 or later for the PM2 support to work.

**Comment by nomiddlename** [comment]
To be clear, is this issue about log4js v1.1.1 not working with pm2, or were you using v2.3.0?

**Comment by yuzhigang33** [comment]
thx so much.
I resolve the  `ID, DATA or TOPIC field is missing` error。

But now ，the api `log4js.shutdown` is not working on cluster mode with `pm2-intercom`.  /(ㄒoㄒ)/~~

**Comment by nomiddlename** [comment]
What happens when you call log4js.shutdown - is there an error? Do you miss log events?

**Comment by yuzhigang33** [comment]
the callback not executed when i call `log4js.shutdown(cb)`

**Comment by yuzhigang33** [comment]
my config:
```
{
    appenders: {
      app: {
        type: 'dateFile',
        filename: 'xx.',
        alwaysIncludePattern: true,
        pattern: 'yyyy-MM-dd.log',
        layout: {
        }
      }
    },
    categories: {
      default: { appenders: ['app'], level: 'debug' }
    },
    pm2: true,
    pm2InstanceVar: 'INSTANCE_ID'
  }
```

pm2.json:
```
{ 
  "apps": [
    { 
      "name": "app",
      "script": "app.js",
      "instances": 0,
      "instance_var": "INSTANCE_ID",
      "exec_mode": "cluster"
    }
  ]
}

```

**Comment by nomiddlename** [comment]
Hi, I've done some testing locally and in my code the shutdown callback definitely gets called. When do you call shutdown?

**Comment by yuzhigang33** [comment]
Oh i'm sorry, yeah, the shutdown callback also gets called in my code. 

My problem is the final log is not flushed. I want to write some log before log4js.shutdown.

is it possible that when i do `pm2 stop` and the ipc has been closed?

**Comment by nomiddlename** [comment]
It would be possible for the process where INSTANCE_ID = 0, that should still be able to write logs after IPC shutdown but before log4js.shutdown, but the other processes will not be able to log anything if pm2-intercom is not running. You'll need log4js v2.3.2 though - 2.3.1 and earlier had a bug where logs from INSTANCE_ID=0 were not being written at all.

**Comment by nomiddlename** [comment]
I'm going to assume your issue is fixed. Please re-open with more details if not. Thanks.

**Comment by manthanbaranwal** [comment]
@nomiddlename  what happens when log4js@1.1.1 is used in pm2 cluster mode (without any pm2 configuration in log4js config) ? Would it behave like single node instead clustor?
