### ISSUE TITLE
When do you roll up log files?

### ISSUE THREAD

**Issue by tangshuang** [nomiddlename/log4js-node#517]
As I known, log4js-node has two mode of rolling files, one is rolled on date and the other one is rolled on file size.

What I want to know is: when rolling up action happens? At the time runing `logger.log`  function? or there is a job to check files in backend?

Could you please give a link of your source code about this?

**Comment by nomiddlename** [comment]
Rolling happens when a `logger.log` call triggers it, yes. There is no background process checking the files. The code can be found in the [streamroller](https://github.com/nomiddlename/streamroller) library. Hope that helps.
