### ISSUE TITLE
Config path not found in log4js

### ISSUE THREAD

**Issue by raheelll** [nomiddlename/log4js-node#530]
Error: ENOENT: no such file or directory, open './config/log4js.json'  
But it's working fine in local system when it's upload on production server it's give error

 please help me.

Thanks 
Raheel Aslam

**Comment by nomiddlename** [comment]
Does the way you execute your application differ between local and production? This is most likely caused by having different values for the current working directory in the two environments.

**Comment by nomiddlename** [comment]
I'm going to close this issue and assume that you fixed your problem. Please re-open if you still think that log4js is the problem. Thanks.
