### ISSUE TITLE
when I start my program, the logs folder will be generated log file, why?

### ISSUE THREAD

**Issue by wadecha** [nomiddlename/log4js-node#535]
appenders: {
      console: {
        type: 'console',
      },
      dateFile: {
        type: 'dateFile',
        filename: 'logs/',
        pattern: 'log.yyyyMMdd.txt',
        alwaysIncludePattern: true,
      },
}

when I start my program, the logs folder will be generated log file, why?

![image](https://user-images.githubusercontent.com/10524259/29803439-78ed03c2-8cae-11e7-85f2-45f9843636b0.png)

**Comment by nomiddlename** [comment]
The dateFile appender will open a file ready for writing. Is there a problem with this?

**Comment by wadecha** [comment]
yeah, I set the default categories appenders is 'redis', not set the dateFile, so where my program start, I donot want it generate a log file.

loggerConfig: {
    categories: {
      default: {
        appenders: ['redis'],
        level: 'info',
      },
    },
    appenders: {
      console: {
        type: 'console',
      },
      dateFile: {
        type: 'dateFile',
        filename: 'logs/',
        pattern: 'log.yyyyMMdd.txt',
        alwaysIncludePattern: true,
      },
      redis: {
        type: 'redis',
        host: '127.0.0.1',
        port: 6379,
        pass: '',
        channel: 'log1',
        category: 'redis',
        layout: {
          type: 'pattern',
          pattern: '%d{yyyy-MM-dd hh:mm:ss:SSS}#%p#%z#%m',
        },
      },
    },
  },

**Comment by nomiddlename** [comment]
I'm not planning to change this, so I'd suggest removing the config for the dateFile appender if you're not going to use it. Thanks.

**Comment by wadecha** [comment]
Thank you for your reply , but user's experience not goods,haha
