### ISSUE TITLE
The console logger print without color and date prefix

### ISSUE THREAD

**Issue by yunnysunny** [nomiddlename/log4js-node#536]
My code test.js:
```javascript
const log4js = require('log4js');
log4js.configure({
    appenders: {
        console:{type:'console', layout: { type: 'colored' }},
    },
    categories: { default: { appenders: ['console'], level: 'trace' } },
    replaceConsole: true
});
const logger = log4js.getLogger('console');
logger.info('test');
```
After run  `node test.js`, it will only print `test`, without date prefix and not colored.

The version of log4js is `2.3.3`.

**Comment by nomiddlename** [comment]
I can't see anything wrong with your configuration here. It should work, and it does on my setup. The coloured layout is the default for the console appender, so you could try removing that part of the configuration. Also note that the stdout appender (the default) has better memory performance than the console appender.

**Comment by nomiddlename** [comment]
I'm going to assume you fixed your issue, but please feel free to re-open with more details if not.
