### ISSUE TITLE
Error: ENFILE file table overflow

### ISSUE THREAD

**Issue by simon-tannai** [nomiddlename/log4js-node#541]
Hello,

I'm using Log4js on node.js server. Today, I got an error who crashed my server:

```
Error: ENFILE: file table overflow, open 'server/logs/request-2017-09-14.log'
    at Error (native)
```
I'm running this node.js server on Docker container (Linux), on a Debian server.

Why this error was throw ? And how to fix it ?

**Comment by nomiddlename** [comment]
This is a problem with your application having too many open files. Without knowing your configuration or application, I can't really say much more. You can increase the number of files your process is allowed to open by using `ulimit` or find out which files it is holding open by using `lsof`.

**Comment by simon-tannai** [comment]
@nomiddlename Thank you for your reply, I did not know the command `lsof`. After have to run the command `lsof +D server/logs/`, I have seen that my logs file was open several times.
I think it's caused by my development: all my objects extends of a `ClassCore` who implement a logger. So I thing if I have 10 object, 10 instances of log4js are created and will open 10 times the same file :S

**Comment by nomiddlename** [comment]
@simon-tannai can I close this issue now? If you still think this is a problem with log4js, let me know.
