### ISSUE TITLE
request for synchronous shutdown method

### ISSUE THREAD

**Issue by JohnChristofolakos** [nomiddlename/log4js-node#542]
The current idiom for flushing the logs and prematurely terminating a process (for example on detecting an uncaught exception):

log4js.shutdown(function() { process.exit(1); });

has the problem that process.exit is called asynchronously. Therefore other ticks can run while, or even after log4js flushes its streams. This may be the root cause of the 'write after end' errors being reported on issue 148 (https://github.com/nomiddlename/log4js-node/issues/148).

More seriously, it makes it impossible for the uncaught exception handler to fulfill its purpose - to shut down the process promptly without any further application processing. Switching to a synchronous appender is not a practical solution for production code.

Request implementation of a synchronous shutdown method that does not return until the shutdown has completed.

**Comment by JohnChristofolakos** [comment]
To be clear, I'm not demanding that someone else rush off and do this work. Just some feedback that this seems to be a good idea - I can create the pull request.

**Comment by nomiddlename** [comment]
Happy to see a pull request for this, although I'm not entirely sure how you can do it.

**Comment by JohnChristofolakos** [comment]
Yeah, me either lol. Done a bit of a deep dive into the formatting aspect, but at this point completely unfamiliar with the I/O aspects. I'll see what I can come up with.

**Comment by JohnChristofolakos** [comment]
On further investigation, you're right Looks like this would have to be a feature of the V8 engine.

Closing this issue.
