### ISSUE TITLE
升级后 log4js 用 import方式 不能用了？？？

### ISSUE THREAD

**Issue by iTwangcj** [nomiddlename/log4js-node#544]
问题：
      如题，升级后 log4js 用 import方式 不能用了？？？打印 输出为 null
老版本："log4js": "^0.6.36" 是可以的
忘解决下 谢谢！

**Comment by cula** [comment]
请帖下你的错误和使用方法？另外，这个project的author好像不是中国人

**Comment by nomiddlename** [comment]
@cula thanks for helping out here - I tried Google translate but it wasn't much help.

**Comment by SergeyJay** [comment]
@nomiddlename he said that the 'import' can't work correctly after he upgraded log4s from version 0.6.36 to the latest,and the print out is null.

**Comment by nomiddlename** [comment]
I'm guessing that this was an issue with the typescript definitions. I'll close this issue, assuming that the changes we made for that fixed it. Please re-open if that is not the problem.
