### ISSUE TITLE
TypeScript definition support problem

### ISSUE THREAD

**Issue by hyq77766177** [nomiddlename/log4js-node#554]
first of all thanks for your logger :)
seems i had a problem after `npm install @types/log4js`, for your version is ahead of types definition. the type of configuration is changed so my code cannot work properly :(
sincerely hope that the support can be update soon, thx

**Comment by nomiddlename** [comment]
Hi, log4js@2.3.5 has a typescript definition from this PR: https://github.com/nomiddlename/log4js-node/pull/553

Could you take a look and see if it helps, please?

**Comment by hyq77766177** [comment]
Thanks for ur comment, it works for my problem, how ever this version seems to be a little... simple.
For example, the `declare` of `Configuration` missed optional property `pm2` and something else.
anyhow thx for contributors ~

**Comment by taoqf** [comment]
https://github.com/nomiddlename/log4js-node/pull/564

**Comment by nomiddlename** [comment]
Please give v2.3.6 a try, the typescript definition has been updated.

**Comment by hyq77766177** [comment]
thanks all of you sweety
