### ISSUE TITLE
some dependencies are deprecated

### ISSUE THREAD

**Issue by naveento** [nomiddlename/log4js-node#557]
After install, i am getting deprecated warnings as follows.
npm WARN deprecated nodemailer@2.7.2: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
+ log4js@2.3.4
added 163 packages in 53.597s

i am using node v8.6.0, npm V5.3.0.

**Comment by nomiddlename** [comment]
Hi, the [FAQ](https://nomiddlename.github.io/log4js-node/faq.html) explains about the nodemailer problem.

**Comment by Phyks** [comment]
For anyone coming across this issue, the up to date link to the FAQ is https://log4js-node.github.io/log4js-node/faq.html :)
