### ISSUE TITLE
CLEAR/DELETE LOG FILES

### ISSUE THREAD

**Issue by webexpertesfera** [nomiddlename/log4js-node#560]
Hello, 

I want to clear or delete logfiles ,when i start running code.
Please ,let me know , is there any way to do this? 

Thankyou

**Comment by nomiddlename** [comment]
The file appenders accept a `flags` option, which is passed to the underlying [node.js file stream](https://nodejs.org/api/fs.html#fs_fs_open_path_flags_mode_callback). A `flags` value of `w` will mean that the files get truncated on opening, which is what I think you want.

**Comment by nomiddlename** [comment]
I'm going to assume that this fixed your problem. Feel free to re-open the issue if it did not.
