### ISSUE TITLE
Latest update breaks build?

### ISSUE THREAD

**Issue by fightingfish18** [nomiddlename/log4js-node#566]
Hello, I ran npm update to update my packages, and it seems that the latest log4js has broken my build. I was updating from a previous 2.x version to 2.3.5.  The error I received was

```
13-Oct-2017 05:18:44 | src/servercore.ts(72,20): error TS2339: Property 'connectLogger' does not exist on type 'typeof "/app/node_modules/log4js/index"'.
```
I also received an error about 'shutdown' does not exist.

I am using TypeScript with the latest TypeScript defs.

Thanks!

**Comment by nomiddlename** [comment]
This should be fixed by PR #564 - once that is merged I'll push out a new version to NPM.

**Comment by nomiddlename** [comment]
Please give v2.3.6 a try - the typescript definition has been updated.

**Comment by fightingfish18** [comment]
That worked, thanks
