### ISSUE TITLE
Email throttle

### ISSUE THREAD

**Issue by awb99** [nomiddlename/log4js-node#569]
I would like to send emails on errors. This is easy to do with log4js. However I want to have all errors that occur within a minute to be sent together.  I found mail-throttle extensions for log4j (Java). Is there a similar extension for Javascript?

**Comment by nomiddlename** [comment]
Does the `sendInterval` option for the [SMTP appender](https://nomiddlename.github.io/log4js-node/smtp.html) do what you want?

**Comment by awb99** [comment]
@nomiddlename Wow! This really works! I honestly have searched a full day before posting this. Thank you so much! Regards Andreas
