### ISSUE TITLE
isTraceEnabled() is missing in the log4js.d.ts file

### ISSUE THREAD

**Issue by maxx07** [nomiddlename/log4js-node#572]
I'm using the v2.3.7 and I noticed that the 
```javascript
isTraceEnabled(): boolean; 
```
is missing in the Logger interface in the type definition file (types/log4js.d.ts) besides the:
```javascript
isDebugEnabled(): boolean;
isInfoEnabled(): boolean;
isWarnEnabled(): boolean;
isErrorEnabled(): boolean;
isFatalEnabled(): boolean;
```
According to api.md file ist should be there. 
Would it be possible to add it to the type definition file?

**Comment by nomiddlename** [comment]
Pushed to npm in version v2.3.8. Let me know if it works.

**Comment by maxx07** [comment]
Works fine, thanks a lot!
