### ISSUE TITLE
Feature: unittestAppender

### ISSUE THREAD

**Issue by osher** [nomiddlename/log4js-node#84]
Hi,

I thought to work on something that would look like this:

Synopsis
-------------

consider your unit-test to contain a test like this:

```
test("my operation emits logs properly", function(done) {

  var config = 
      { category: "my-operation"
      , maxEntries : 200   //keeps in memory maximum 200 entries per category 
      };

      testAppender = log4js.addAppender( log4js.unitestsAppender(config), "my-operation" ),
      myAutits = testAppender.getAudits();

  //this operation is assumed to send an entry to getLogger("my-operation")
  operationThatShouldEmitLogs(function(err, result){
      log4js.removeAppender( testAppender);

      assert.ok( 
        myAutits.contains(
          { level    : /INFO|WARN/
          , text     : /(Operation succeeded|Operation failed)/
          , category : "my-operation"
          }
        )
      );
});
```

or 

```
var vows = require('vows')
   , claim = require('assert')
   ;

vows.describe(
   "my great utility"
).addBatch(
   { "my operation" :
     { topic: 
        function(){
           var cb = this.callback;
           var config = 
               { category: "my-operation"
               , maxEntries : 200   //keeps in memory maximum 200 entries per category 
               };

           testAppender = log4js.addAppender( log4js.unitestsAppender(config), "my-operation" ),
           myAutits = testAppender.getAudits();

           //this operation is assumed to send an entry to getLogger("my-operation")
           operationThatShouldEmitLogs( function(err,result) {
                  log4js.removeAppender( testAppender);
                  cb(err,result);
            });     
        }
     , "should emit loggs properly" :
        function(err, audit){
           assert.isUndefined(err);
           assert.isObject(audit);
           assert.ok( 
             myAutits.contains(
               { level    : /INFO|WARN/
               , text     : /(Operation succeeded|Operation failed)/
               , category : "my-operation"
               }
             )
           );
        }
     }
  }
);

```
API
-----
I'm not final on the API design, and would love to talk about it with somebody
what I got now - and I'm not sure if its fully compatible with the underlying infra (log4js) is:

* unitestsAppender 
-- implements Logger
-- getAudits(0) - returns unitTestsAudits module

* unitTestsAudits
-- contains(query), where query can optionally specify level, text and category 
   (why category? in case you audit few together)

Technicalities
--------------------------------
I looked on ./lib/appenders/console - it looks quite easy to add an appender that will gather the entries in memory, so they can later be searched for assertions.
My real problems are - 
-  technically how to do it with GIT and GITHUB...
- I can't run the unit-tests - perhaps because I'm a windows user and the `npm install` fiddles with dependencies that are not cross-platform.

*GITHUB*

I'm still trying to take my first successful steps with github, with cloning a repo, working on a solution and sumbitting a pull request that is not editing a file on the github web editor...

*Windows*

I can offer help in making component cross-platform, the minuet we figure how to run it on windows, or how to ignore it if it's just wont...

I'd appreciate some help here... :)

**Comment by nomiddlename** [comment]
Cleaning up old issues.
