### ISSUE TITLE
Allow configuration of colors for each level

### ISSUE THREAD

**Issue by vjpr** [nomiddlename/log4js-node#90]
1. The config should allow levels to be associated with a color.
2. These colors should then been accessible when creating a custom pattern.

Not sure best way to add colors to patterns though.

**Comment by nomiddlename** [comment]
Duplicate of #254 - fix for that should fix this one.

**Comment by stanleyxu2005** [comment]
Great to find this issue report. Please consider provide individual colors for log levels and individual colors for categories.

**Comment by nomiddlename** [comment]
Released in version 2.0.0
