### ISSUE TITLE
Allow objects to be formatted with `util.inspect`

### ISSUE THREAD

**Issue by vjpr** [nomiddlename/log4js-node#92]
When passing an object to a logging function, `util.inspect` allows you to control the recursion depth that it prints an objects properties, and also add colors to the output.

This would be a configuration option for the console appender.

**Comment by FredKSchott** [comment]
you could do this with the pattern layout with tokens, check out https://github.com/nomiddlename/log4js-node/blob/9fe32d06e30680b31a558fd96ed3bfe048da3051/examples/patternLayout-tokens.js

**Comment by nomiddlename** [comment]
layouts use `util.format` now, so I think this one can be closed.
