### ISSUE TITLE
possible file descriptor leak with 'reloadSecs'

### ISSUE THREAD

**Issue by freedaxin** [nomiddlename/log4js-node#99]
After reloaded, old file descriptor is not closed, and there's no exports method for this purpose.

**Comment by nomiddlename** [comment]
This will be "fixed" in version 2.x - because I've removed the reloading feature, as it wasn't implemented in a safe way. Best to let users implement themselves, or implement later using the `shutdown` and `configure` functions.

**Comment by nomiddlename** [comment]
Released in version 2.0.0 (well, removed rather than released)
